```{r}
source("_setup.R")
```

## Modelado Bayesiano. {#sec-bayes-2}

\tiny
```{r}
#| cache: true
#| echo: true

brm_subject_formula <- Response ~ 1 + (1 | Subject)
brm_subject <-
    brm(
        brm_subject_formula,
        data = df_clean,
        family = cumulative("logit"),
        sample_prior = TRUE,
        file = "models/brm_subject",
        file_refit = "on_change"
    )
summary(brm_subject)
```

```{r}
#| echo: true
#| cache: true
brm_treat.period.subject.question <- brm(
    Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Question),
    data = df_clean,
    family = cumulative("logit"),
    sample_prior = TRUE,
    file = "models/brm_treat.period.subject.question",
    file_refit = "on_change"
)
summary(brm_treat.period.subject.question)
```

```{r}
#| echo: true
#| cache: true
brm_treat.period.subject_question <- brm(
    Response ~ Treat * Period + (1 + Treat | Subject) + (1 | Question),
    data = df_clean,
    family = cumulative("logit"),
    sample_prior = TRUE,
    file = "models/brm_treat.period.subject_question",
    file_refit = "on_change"
)
summary(brm_treat.period.subject_question)
```

```{r}
#| echo: true
#| cache: true
brm_cs.treat.subject.question <- brm(
    Response ~ 1 + cs(Treat) + (1 | Subject) + (1 | Question),
    data = df_clean,
    family = cumulative("logit"),
    sample_prior = TRUE,
    file = "models/brm_cs.treat.subject.question",
    file_refit = "on_change"
)
summary(brm_cs.treat.subject.question)
```



```{r}
#| eval: false
conditions <- make_conditions(brm_treat.period.subject.question, vars = c("Question"))
conditional_effects(brm_treat.period.subject.question, categorical = T, effects = "Treat", conditions = conditions, re_formula = NULL, ask = F, robust = T, prob = 0.5)
pp_check(brm_treat.period.subject.question, type = "bars_grouped", group = "Question", ndraws = 1000)

```

```{r}
#| echo: true
#| cache: true
brm_treat_question_subject_question <- brm(
    Response ~ 1 + Treat + (1 | Question) + (1 | Subject:Question),
    data = df_clean,
    family = cumulative("logit"),
    sample_prior = TRUE,
    file = "models/brm_treat_question_subject_question",
    file_refit = "on_change"
)
summary(brm_treat_question_subject_question)
```


```{r}
#| echo: true
#| cache: true
brm_treat_question_subject <- brm(
    Response ~ 1 + Treat + (1 | Question) + (1 | Subject),
    data = df_clean,
    family = cumulative("logit"),
    sample_prior = TRUE,
    file = "models/brm_treat_question_subject",
    file_refit = "on_change"
)
summary(brm_treat_question_subject)
```

_
```{r}
#| echo: true
#| cache: true
brm_period.treat.subject_question <- brm(
    Response ~ Period * Treat + (1 + Treat | Subject) + (1 | Question),
    data = df_clean,
    family = cumulative("logit"),
    sample_prior = TRUE,
    file = "models/brm_period.treat.subject_question",
    file_refit = "on_change"
)
summary(brm_period.treat.subject_question)
```

```{r}
#| echo: true
#| cache: true
brm_period.treat_subject_question <- brm(
    Response ~ Period * Treat + (1 | Subject) + (1 | Question),
    data = df_clean,
    family = cumulative("logit"),
    sample_prior = TRUE,
    file = "models/brm_period.treat_subject_question",
    file_refit = "on_change"
)
summary(brm_period.treat_subject_question)
```

```{r}
#| echo: true
#| cache: true
brm_period.treat.question_subject <- brm(
    Response ~ Period * Treat + (1 | Subject) + (1 + Treat | Question),
    data = df_clean,
    family = cumulative("logit"),
    sample_prior = TRUE,
    file = "models/brm_period.treat.question_subject",
    file_refit = "on_change"
)
summary(brm_period.treat.question_subject)
```


```{r}
#| echo: true
#| cache: true
brm_thres.question_period.treat.subject <- brm(
    bf(Response | thres(gr = Question) ~ Period * Treat + (1 + Treat | Subject)),
    data = df_clean,
    family = cumulative("logit"),
    sample_prior = TRUE,
    file = "models/brm_thres.question_period.treat.subject",
    file_refit = "on_change"
)
summary(brm_thres.question_period.treat.subject)
```

```{r}
#| echo: true
#| cache: true
brm_period.treat.subject_question.disc <- brm(
    bf(
        Response ~ Period * Treat + (1 + Treat | Subject) + (1 | q | Question),
        disc ~ 1 + (1 | q | Question)
    ),
    data = df_clean,
    family = cumulative("logit"),
    sample_prior = TRUE,
    file = "models/brm_period.treat.subject_question.disc",
    file_refit = "on_change",
    prior = prior("constant(1)", class = "sd", group = "Subject") +
        prior("normal(0, 3)", class = "sd", group = "Question") +
        prior("normal(0, 1)", class = "sd", group = "Question", dpar = "disc")
)
summary(brm_period.treat.subject_question.disc)
```

```{r}
#| echo: true
#| cache: true
brm_acat_cs.treat.subject.question <- brm(
    Response ~ 1 + cs(Treat) + (1 | Subject) + (1 | Question),
    data = df_clean,
    family = acat("logit"),
    sample_prior = TRUE,
    file = "models/brm_acat_cs.treat.subject.question",
    file_refit = "on_change"
)
summary(brm_acat_cs.treat.subject.question)
```

```{r}
#| echo: true
#| cache: true
brm_treat.period.subject.question <- brm(
    Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Question),
    data = df_clean,
    family = cumulative("logit"),
    sample_prior = TRUE,
    file = "models/brm_treat.period.subject.question",
    file_refit = "on_change"
)
summary(brm_treat.period.subject.question)
```

```{r}
#| echo: true
#| cache: true
LOO(
    brm_subject,
    brm_period.treat_subject_question,
    brm_treat.period.subject.question,
    brm_cs.treat.subject.question,
    brm_treat_question_subject,
    brm_treat_question_subject_question,
    brm_period.treat.subject_question,
    brm_thres.question_period.treat.subject,
    brm_period.treat.subject_question.disc,
    brm_acat_cs.treat.subject.question,
    brm_period.treat.question_subject
)
```
\normalsize



