# Full list of options on https://quarto.org/docs/reference/projects/books.html
project:
  type: book
  output-dir: docs
execute:
  echo: false
  warning: false

book:
  title: "Utilización de técnicas
multivariantes para el estudio del
aprendizaje de la mejora de la
accesibilidad en el subtitulado de
vídeos"
  author: "Javier Pérez Arteaga"
  date: "10/03/2023"
  description: "TFM UNED Máster en Ingeniería y Ciencia de Datos"
  chapters:    
    - index.qmd
    - 2.qmd
    - 3.qmd
    - 4.qmd
    - 5.qmd
    - 6.qmd
    - 7.qmd
  appendices:
    #- 75-Preprocesado.qmd
    #- 76-Setup.qmd
    - 77-Contrasts.qmd
    #- 78-Bayesiano.qmd

  cover-image: "images/logo-cover.png"
  favicon: "images/logo.png"
  downloads: pdf
  sharing: [twitter, facebook]
  search: true

# Bibliography file
bibliography: references.bib
# Language
lang: es
otherlangs: [en-US]

opts_chunk:
    comment: ""
    collapse: true


format:

  html:
    theme: cosmo
    csl: https://www.zotero.org/styles/chicago-author-date

  pdf: 
    fig-width: 7  
    fig-pos: h 
    # Paper, font
    papersize: A4
    fontsize: 12pt
    # Fonts installed by a package. LaTeX tex-gyre package must be installed for:
    mainfont: texgyretermes            # Times New Roman for the text
    mathfont: texgyretermes-math.otf   # Times New Roman for equations
    # memoir Style
    MemoirChapStyle: daleif1           # or companion with large margins
    MemoirPageStyle: Ruled             # or companion with large margins
    # Margins
    largemargins: false                # or true for large margins
    smallmargin: 1.5in                 # outer margin (small).
    largemargin: 3in                   # outer margin (large)
    marginnote:  1.8in                 # note width in large margin
    spinemargin: 1.5in                 # spine margin. Reduce to 1.2 with large margins.
    uppermargin: 1.5in                 # upper margin
    lowermargin: 1in                   # lower margin

    # Table of contents
    toc-depth: 2
    toc-title: Contents
    # Section numbering
    secnum-depth: section
    # List of tables / Figures
    lot: true
    lof: true
    # Chapter summary text
    chaptersummary: In a Nutshell
    # Figure cropping may be set to false if ghostscript is not installed
    fig_crop: true
    # URL color
    urlcolor: blue

    # Title page...
    maintitlepage:
      epigraph: |
        This document is reproducible thanks to:
        \begin{itemize}
          \item \LaTeX and its class memoir (\url{http://www.ctan.org/pkg/memoir}).
          \item R (\url{http://www.r-project.org/}) and RStudio (\url{http://www.rstudio.com/})
          \item bookdown (\url{http://bookdown.org/}) and memoiR (\url{https://ericmarcon.github.io/memoiR/})
        \end{itemize}
      credits: |
        Name of the owner of the logo

        \url{http://www.company.com}

        An explanatory sentence.
        Leave an empty line for line breaks.
      logo: "images/logo.png"
    # ... or a PDF cover
    # pdftitlepage: images/cover.pdf

    # Bibliography
    cite-method: biblatex
    biblatexoptions:
      - backend=biber
      - style=authoryear-ibid  # or verbose-inote with large margins
      #- pageref=true          # uncomment for verbose-inotes style
      - isbn=false
      - backref=true
      - giveninits=true
      - uniquename=init
      - maxcitenames=2
      - maxbibnames=150
      - sorting=nyt
      - sortcites=false
    longbibliography: false    # if true, two columns and smaller font in PDF

    # Image files folder
    graphicspath: images

    # Keep the tex file
    keep-tex: true

    # Do not modify below
    documentclass: memoir
    classoption:
      - extrafontsizes
      - onecolumn
      - openright
    mainfontoptions:
      - Extension=.otf
      - UprightFont=*-regular
      - BoldFont=*-bold
      - BoldItalicFont=*-bolditalic
      - ItalicFont=*-italic
    include-in-header:
      # File content can be modified by the user
      - "latex/preamble.tex"
    template-partials:
      - "partials/pandoc.tex"
      - "partials/title.tex"
      - "partials/before-body.tex"
      - "partials/toc.tex"
      - "partials/biblio.tex"
      - "partials/after-body.tex"
    csquotes: true
    link-citations: true
