project:
  type: book

lang: es
book:
  title: "TFM"
  author: "Javier Pérez"
  date: "14/3/2023"
  chapters:
    - index.qmd
    - anoveOne.qmd
    - anoveTwo.qmd
    - anoveThree.qmd
    #- intro.qmd
    #- summary.qmd
    - references.qmd

bibliography: references.bib

execute:
  echo: false

opts_chunk:
    comment: ""
    collapse: true

format:
  html:
    toc: true
    toc-depth: 2
    theme: cosmo
  pdf:
    toc: true
    toc-depth: 2
    lof: true
    lot: true
    cite-method: biblatex
    biblatexoptions: [backend=biber, style=authoryear,citestyle=authoryear]
    documentclass: memoir


