
```{r}
#| warning: false
#| include: false
#| echo: false
#| cache: false

library(car)
library(dplyr)
library(forcats)
library(ggplot2)
library(ggthemes)
library(lme4)
library(lmerTest)
library(magrittr)
library(multcomp)
library(ordinal)
library(purrr)
library(stringr)
library(readr)
library(testit)
library(tidyr)
library(tidyverse)
library(broom)
library(emmeans)
```

```{r}
#| warning: false
#| include: false
#| echo: false
#| cache: false

#| echo: false

# Leemos el tibble preprocesado
test_df <- read_delim("./data/preprocess/test.csv", delim = ",", show_col_types = FALSE)


# Eliminamos aquellos usuarios que no han hecho uno de los test
test_df %<>%
    group_by(User) %>%
    mutate(Rows = n()) %>%
    filter(Rows > 1) %>%
    ungroup()

# Renombramos columnas de acuerdo con Lawson y ponemos en formato largo
test_df



##### SAVE TO FILE #####

write_csv(test_df, "./data/preprocess/test.csv")

```

```{r}
#| echo: false
df <- test_df %>%
    mutate(Period = as.factor(if_else(Test == "01", 1, 2)), Treat = as.factor(if_else(Group == "A" & Test == "01" | Group == "B" & Test == "02", "A", "B")), Group = as.factor(if_else(Group == "A", "AB", "BA")), Subject = as.factor(User)) %>%
    dplyr::select(Group, Period, Treat, Subject, starts_with("Q")) %>%
    mutate_at(vars(starts_with("Q")), ~ (. + 1) %% 6) %>%
    pivot_longer(cols = all_of(starts_with("Q")), names_to = "Question", values_to = "Response") %>%
    mutate(Question = relevel(as.factor(Question), ref = "Q18"), Response = factor(Response, ordered = TRUE)) %>%
    arrange(Subject, Period, Question)

write_csv(df, "./data/preprocess/test_lg.csv")
df_all <- df
df_clean <- df %>% filter(Response != 0)
df_0 <- df %>% filter(Response == 0)
```

