{
  "hash": "6fed932bf9417eb02629c71fb4157c8a",
  "result": {
    "markdown": "::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n\n# Modelado estadístico {#sec-modelado}\n\nEste capítulo comienza con un análisis exploratorio de los datos. Continúa\nproponiendo diversas formas de adecuar el modelado estadístico\nque se explicó en el Marco Teórico (ver @sec-arte) al diseño del experimento\ndel subtitulado. La selección de los modelos se realiza en el @sec-resultados.\n\n## Análisis Exploratorio {#sec-eda}\n\n\nComo se explica en la @tbl-variables, al subtitulado se le denomina tratamiento y a sus niveles (correcto e incorrecto) se les ha llamado $A$ y $B$ sin hacer ninguna conjetura de cual de los dos es el subtitulado correcto. El grupo con secuencia $AB$ será el que primero vio el vídeo con subtitulado $A$ y luego el $B$. Análogamente, el grupo con secuencia $BA$ vio los vídeos en orden inverso. Recuérdese que el nivel 0 de respuesta se corresponde con \"No sé / No contesto\" (ver @tbl-likert-levels). Tras eliminar los test de los 19 estudiantes que no dieron su consentimiento para participar en el estudio y los de los 24 estudiantes que no realizaron el segundo test, las dos cohortes están equilibradas ya que hay 43 estudiantes que realizaron el test con secuencia $AB$ y 44 con secuencia $BA$.\n\n\n\n::: {.cell}\n\n:::\n\n\n\n### Análisis de la calidad de los datos\n\nEn esta sección se analiza si hay test que tienen valores de respuesta que puedan resultar anómalos. \nEn los test no se ha observado ningún valor nulo ni erróneo.\n\n\n\n::: {.cell}\n\n:::\n\n\n\nEl campo `LastTry` contiene la fecha y hora de realización del test. Con esta información se puede conocer el tiempo que transcurrió desde que un estudiante rellenó el primer test hasta que completó el segundo. Dado que los vídeos duran 43 segundos y hay 18 ítems, se puede estimar el tiempo medio que cada estudiante empleó en contestar cada ítem suponiendo que haya visto el segundo vídeo completo. La @tbl-washout muestra que hay algunos test en los que los estudiantes emplearon un tiempo muy breve en contestar\n^[Hay que tener en cuenta que la duración de vídeo es de algo más de 40 segundos y que los estudiantes tienen que contestar un test de 18 ítems.].\n\n\n\n::: {#tbl-washout .cell tbl-cap='Tiempos de realización de la segunda actividad de duración inferior a 2 minutos.'}\n::: {.cell-output-display}\n\\begin{longtable}{rlcc}\n\\toprule\nSubject & Test & Spent time (secs) & Time by Item (secs) \\\\ \n\\midrule\n893 & B & 56 & 0.72 \\\\ \n1020 & B & 78 & 1.94 \\\\ \n85 & A & 102 & 3.28 \\\\ \n4 & B & 103 & 3.33 \\\\ \n110 & A & 107 & 3.56 \\\\ \n1034 & A & 118 & 4.17 \\\\ \n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n\nLa @fig-distinct muestra que hay 28\ntest en los que el estudiante contestó a todos los ítems usando únicamente 2 respuestas diferentes.\nAdemás hay 13 \n    test en los que se contestaron todos los ítems con 1 respuesta.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Número de respuestas diferentes en un mismo test.](4_files/figure-pdf/fig-distinct-1.pdf){#fig-distinct}\n:::\n:::\n\n\n\nLa tabla @tbl-distinct2 muestra los test de respuesta única y el valor de esa respuesta. Se aprecia que la mayoría de estos test tienen valor de respuesta 4, la secuencia mayoritaria es la $BA$ y el test el $A$. El estudiante 4 responde ambos test utilizando el mismo valor de respuesta en todos los ítems.\n\n\\clearpage\n\n\n\n::: {#tbl-distinct2 .cell tbl-cap='Test en los que todos los ítems se contestan con el mismo valor de respuesta.'}\n::: {.cell-output-display}\n\\begin{longtable}{rllr}\n\\toprule\nResponse & Seq & Test & Subject \\\\ \n\\midrule\n2 & AB & A & 4 \\\\ \n2 & AB & B & 4 \\\\ \n3 & BA & B & 734 \\\\ \n3 & BA & A & 803 \\\\ \n3 & BA & A & 33 \\\\ \n3 & BA & A & 229 \\\\ \n4 & AB & A & 35 \\\\ \n4 & AB & A & 76 \\\\ \n4 & AB & B & 523 \\\\ \n4 & BA & B & 85 \\\\ \n4 & BA & A & 901 \\\\ \n4 & BA & A & 808 \\\\ \n4 & BA & A & 871 \\\\ \n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\nLa @fig-compare presenta la distribución de la cantidad de respuestas cuyo valor cambia entre los dos test que realiza cada estudiante. La mayoría de los estudiantes cambian entre uno y otro test entre 11 y 17 respuestas. Tan solo 1 estudiante respondió a todos los ítems con el mismo valor en los dos test. Por otro lado, no hay test que tengan un número excesivo de contestaciones \"No sé/No contesto\" (ver @tbl-noanswer).\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Número de respuestas diferentes entre los test para cada estudiante.](4_files/figure-pdf/fig-compare-1.pdf){#fig-compare}\n:::\n:::\n\n\n\n\\clearpage\n\n\n\n::: {#tbl-noanswer .cell tbl-cap='Los 5 test con más respuestas \\'No sé / No contesto\\''}\n::: {.cell-output-display}\n\\begin{longtable}{lrr}\n\\toprule\nTest & Subject & Total answers by test \\\\ \n\\midrule\nA & 231 & 5 \\\\ \nB & 339 & 5 \\\\ \nB & 346 & 5 \\\\ \nB & 1174 & 5 \\\\ \nA & 1187 & 4 \\\\ \n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\nEn resumen, se constata que algunos test tienen valores que no parecen muy razonables. Por ejemplo, no parece razonable realizar la actividad en menos de 120 segundos. Además en algunos test hay poca variabilidad en las respuestas. Sin embargo, no son muchos los test con estas características así que se ha decidido mantener estos datos a pesar de que se pueda dudar de si en ellos los estudiantes contestaron con la debida atención y diligencia.\n\n### Comparación de los subtítulos $A$ y $B$ entre grupos {#sec-eda-3}\n\nLa @fig-diff presenta una forma de comparar los dos test realizados por los estudiantes. Para cada estudiante se comparó ítem a ítem sus dos test y se contabilizó la diferencia entre el número de ítems en los que la puntuación en el segundo vídeo fue superior y en los que lo fue inferior (las que no variaron de puntuación no se consideraron). En el eje $x$ se muestran las diferencias entre respuestas. Cantidades negativas indican que hay más respuestas en el segundo de los test que han empeorado respecto al primero de las que han mejorado. En el eje $y$ se representa el número de estudiantes para cada diferencia. Esta frecuencia se representa en negativo cuando la diferencia en el eje x sea negativa para facilitar la comparación^[En la comparación se han omitido aquellas respuestas en las que el estudiante contestó \"No sé / No contesto\" en el ítem correspondiente de uno de los test.]. Esto es una forma de evaluar si el estudiante valoró mejor el segundo vídeo que el primero. \n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Diferencias en las respuestas entre test por estudiante y grupo.](4_files/figure-pdf/fig-diff-1.pdf){#fig-diff fig-pos='h'}\n:::\n:::\n\n\n\nSe aprecia que en el grupo $AB$ las diferencias tienden a ser negativas y en el $BA$ positivas. Esto estaría indicando que los estudiantes valoran mejor el subtitulado de nivel $A$ en ambas secuencias. Por ello, es esperable que las respuestas de los estudiantes del grupo $AB$ hayan empeorado y que las diferencias sean negativas y que lo contrario haya sucedido con las del grupo $BA$. La diferencia más frecuente en el grupo $AB$ es 12 y en el grupo $BA$ este valor es 11.\nResulta llamativo que haya estudiantes cuyas contestaciones estén tan alejadas de la tendencia de su grupo. En la @tbl-diff se muestran los tiempos que han transcurrido entre la realización de los test de aquellos estudiantes cuyas respuestas difieren de forma importante de su grupo. Son aquellos que aparecen en azul en la secuencia $AB$ y en rojo en la secuencia $BA$. Se observa que casi todos son tiempos entre actividades muy cortos. En cualquier caso y, como no son muchos, se ha decidido no eliminarlos y realizar el análisis con ellos.\n\n\n\n::: {#tbl-diff .cell tbl-cap='Estudiantes que tienen diferencias en sus respuestas muy alejadas de la tendencia de su grupo.'}\n::: {.cell-output-display}\n\\begin{longtable}{lrrc}\n\\toprule\nSeq & Subject & Diff & Minutes \\\\ \n\\midrule\nAB & 1020 & 17 & 1.3 \\\\ \nAB & 75 & 7 & 3.33 \\\\ \nBA & 650 & -10 & 50345.95 \\\\ \nBA & 85 & -12 & 1.7 \\\\ \n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {#tbl-resume .cell tbl-cap='Resumen de frecuencias de respuesta.'}\n::: {.cell-output-display}\n\\begin{longtable}{cccrrrrrr}\n\\toprule\n &  &  &  & \\multicolumn{5}{c}{Response} \\\\ \n\\cmidrule(lr){5-9}\nSeq & Period & Treat & 0 & 1 & 2 & 3 & 4 & 5 \\\\ \n\\midrule\nAB & 1 & A & 39 & 2 & 25 & 71 & 203 & 434 \\\\ \nAB & 2 & B & 43 & 87 & 185 & 121 & 172 & 166 \\\\ \nBA & 1 & B & 40 & 76 & 174 & 127 & 237 & 138 \\\\ \nBA & 2 & A & 30 & 2 & 30 & 64 & 345 & 321 \\\\ \n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\n\nEn la @tbl-resume se muestra la frecuencia absoluta del valor de respuesta para cada grupo y test en todos los ítems. Esta es otra forma de comparar los niveles de subtitulado. La @fig-freqs muestra la misma información gráficamente y con frecuencias relativas. En esta figura se pueden apreciar algunas cuestiones interesantes:\n\n* El tratamiento (subtitulado) con nivel $A$ presenta claramente mayores valores de respuesta que el $B$ como ya se había visto (ver @fig-diff).\n\n* En general los dos grupos ($AB$ y $BA$) muestran bastante acuerdo en el subtitulado en ambos niveles: En el nivel de tratamiento $A$ los dos grupos tienen una frecuencia relativa similar de respuestas positivas (valores 4 y 5). El grupo $AB$ tiene un 82% de respuestas positivas y el grupo $BA$ 84%. No obstante, el grupo $AB$ tiene más respuestas con valor 5 que el grupo $BA$ (56% frente a 41%). La valoración es también similar entre grupos en el nivel de tratamiento $B$: el grupo $AB$ tiene 44% de respuestas positivas y 47% el grupo $BA$. Las valoraciones negativas (1, 2), la neutra (3) y la 'No sé / No contesto' (0) son también muy similares en ambos grupos.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Frecuencias relativas de las respuestas al test.](4_files/figure-pdf/fig-freqs-1.pdf){#fig-freqs fig-pos='h'}\n:::\n:::\n\n\n\nEl análisis marginalizado de tratamiento, secuencia y periodo tiene estos resultados referidos a los ítems con contestación positiva (4, 5):\n\n* El tratamiento $A$ tiene un 83% marginalizado de respuestas positivas frente al 46% del tratamiento $B$.\n\n* El periodo 1 tiene un 65% marginalizado de respuestas positivas frente al 64% del periodo 2.\n\n* Finalmente, la secuencia $AB$ tiene un 63%\nde respuestas positivas frente 66% de la secuencia $BA$.\n\n\n### Análisis de los ítems\n\n\n\n::: {.cell}\n\n:::\n\n\n\nEl gráfico @fig-levels muestra la frecuencia relativa por grupo y por test de los ítems clasificados por niveles de respuesta, considerando que:\n\n * Los niveles 1 y 2 se consideran valoraciones negativas.\n * El nivel 3 se considera neutro.\n * Los niveles 4 y 5 se consideran positivos.\n * El nivel 0 (\"No sé / No contesto\") se excluye en este análisis.\n\nSe muestra en primer lugar el ítem 18 por ser una valoración global del subtitulado y que resume la opinión que sobre el mismo tiene el estudiante. Se vuelve a constatar que el subtitulado $A$ es mejor valorado por los estudiantes, pero ahora se confirma que en los 18 ítems ambos grupos tienen más puntuaciones positivas y menos negativas en el subtitulado $A$ que en el $B$. También se vuelve a constatar que los dos grupos valoran de forma muy similar los dos niveles de subtitulado en todos los ítems. En el nivel de subtitulado $A$ los ítems $Q15$, $Q16$ y $Q17$ obtienen relativamente peores valoraciones (consultar la @tbl-likert-scale para ver el texto de los ítems) y estas son similares en ambos subtitulados. Hay algunos ítems que son valorados de forma muy positiva incluso en el nivel de subtitulado $B$ (por ejemplo $Q04$ o $Q13$). Por último, los ítems $Q05$ y $Q09$ (también la $Q14$ pero solo para el grupo $BA$) tienen una valoración muy negativa en el nivel de subtitulado $B$.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Frecuencias relativas de las respuestas por ítem.](4_files/figure-pdf/fig-levels-1.pdf){#fig-levels width=\\\\widthw}\n:::\n:::\n\n\n\n\n\nEn la @tbl-no-response se muestran las contestaciones \"No sé / No contesto\" por subtitulado e ítem\n^[Solo se muestran los ítems que tienen respuestas \"No sé / No contesto\" en alguno de los subtitulados.]. Se observa que hay relativamente pocas contestaciones \"No sé / No contesto\" y que éstas se concentran en los ítems $Q14$, $Q15$, $Q16$ y $Q17$.\nEl número de respuestas \"No sé / No contesto\" está razonablemente equilibrado entre\nsubtitulados excepto en el ítem $Q10$. \n\n\\small\n\n\n::: {#tbl-no-response .cell tbl-cap='Contestaciones \"No sé / No contesto\" por nivel de subtitulado e ítem'}\n::: {.cell-output-display}\n\\begin{longtable}{rrrrrrrrrrrrr}\n\\toprule\nQ03 & Q05 & Q06 & Q08 & Q09 & Q10 & Q11 & Q12 & Q13 & Q14 & Q15 & Q16 & Q17 \\\\ \n\\midrule\n\\multicolumn{13}{l}{A} \\\\ \n\\midrule\n1 & 0 & 1 & 3 & 1 & 0 & 1 & 1 & 0 & 11 & 11 & 22 & 17 \\\\ \n\\midrule\n\\multicolumn{13}{l}{B} \\\\ \n4 & 1 & 0 & 1 & 0 & 8 & 2 & 4 & 1 & 10 & 15 & 25 & 12 \\\\ \n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\\normalsize\n\n## Modelos utilizados {#sec-modelos-utilizados}\n\nEs esta sección se concreta la forma de aplicar los modelos presentados en el Marco teórico (ver @sec-arte) en la actividad de subtitulado.\n\n### Comparación con *Odds Ratio* [^or] {#sec-or-2}\n\n[^or]: Esta técnica se ha omitido en el Marco teórico por considerarla conocida por el lector. Si se desea ampliar información se puede consultar @agresti2010 [p. 18].\n\nLa métrica *\\gls{odds ratio}* ($OR$) permite medir la asociación entre dos variables con dos niveles cada una. En el diseño de experimento que se está analizando, los factores $Treat$, $Period$ y $Seq$ tienen todos 2 niveles y se puede contrastar si hay interacción entre cada par de factores para cada nivel de respuesta. Es decir, se contrasta la hipótesis $H_0: OR=1$ de ausencia de asociación frente a $H_1: OR \\neq 1$ de existencia de asociación en algún nivel de respuesta. Por ejemplo, el $OR$ para el nivel respuesta $r$ entre subtítulos y secuencias se define de la siguiente forma:\n\n$$\nOR_{(Treat, Seq \\mid Response=r)}=\\frac{\n    \\frac{\n            P(Treat=A \\mid Seq=AB, Response=r)\n        }{\n            P(Treat=B \\mid Seq=AB, Response=r)\n        }\n    }\n    {\\frac{\n        P(Treat=A \\mid Seq=BA, Response=r)\n        }{\n        P(Treat=B \\mid Seq=BA, Response=r)\n    }\n}\n$$\n\nSi los $\\gls{odds}$ son similares en cada nivel de respuesta, se acepta la hipótesis nula de que los grupos responden de forma similar a cada nivel de subtitulado y secuencia. En la @sec-or-3 se pueden consultar los resultados obtenidos. En esta misma sección se hace un test similar pero entre subtitulado y periodos. Para realizar el contraste de hipótesis se usa la función $loddsratio$ del paquete `vcd` [ver @vcd].\n\n\n### Regresión Logística {#sec-logistica-2}\n\nEn la @sec-logistica se presentó el fundamento teórico de la \\gls{Regresión Logística}. En esta sección se justifica el uso de este modelo y se ajustan y comparan varios modelos. La variable respuesta se compone de 5 valores ordenados. Esto imposibilita usar directamente la Regresión Logística ya que requiere que la variable de respuesta sea dicotómica. No obstante, se puede comparar la respuesta que cada estudiante dio a cada uno de los subtitulados y comprobar si ha mejorado. Esto producirá una variable de respuesta binaria que permitirá el uso de la Regresión Logística. No obstante, esta transformación reducirá la cantidad de datos disponibles a la mitad e impedirá analizar el \\gls{efecto periodo} ya que al comparar los subtitulados, desaparece el periodo. Se ha creado una variable `Improve` con dos valores posibles: 1 cuando el estudiante valoró el ítem mejor en el subtitulado $A$ que en el $B$, 0 si empeoró o puntuó igual. Si en uno de los test contestó un ítem con \"No sé / No contesto\", se elimina ese ítem.\n\n\n\n::: {.cell}\n\n:::\n\n\nSe ajusta el modelo con la secuencia como predictor:\n\n\\scriptsize\n\n::: {.cell}\n\n```{.r .cell-code}\nglm_improve_seq <- glm(Improve ~ 1 + Seq, family = \"binomial\", data = df_improve)\nsummary(glm_improve_seq)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = Improve ~ 1 + Seq, family = \"binomial\", data = df_improve)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  0.37858    0.07635   4.958 7.11e-07 ***\nSeqBA       -0.05137    0.10668  -0.481     0.63    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1967.2  on 1450  degrees of freedom\nResidual deviance: 1966.9  on 1449  degrees of freedom\nAIC: 1970.9\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\\normalsize\n\nSe constata que el coeficiente del intercepto es positivo y significativo (0.38). El intercepto es el $log\\ odds$ de mejorar la valoración en $A$ sobre $B$ respecto a empeorar la valoración. La probabilidad de que la respuesta a un ítem sea mejor en el subtitulado $A$ que en el $B$ es 0.59. La secuencia no resulta significativa y además añadirla apenas reduce la \"deviance\", por lo que el modelo nulo sin predictores resulta más parsimonioso.\n\nOtra forma de plantear una Regresión Logística es crear una variable de respuesta dicotómica que tenga valor 1 cuando la respuesta sea positiva (valores 4 ó 5) y cero cuando no lo sea (valores 1, 2 ó 3). En la @sec-ordinal-3 se comentan los resultados de este modelo.\n\n### Regresión Ordinal {#sec-ordinal-2}\n\nEn la @sec-ordinal se presentó el fundamento teórico de la Regresión Ordinal Acumulativa ($CM$). En esta sección se comprueban las hipótesis de este modelo para el experimento del subtitulado de vídeos y se ajustan varios modelos que tratan de predecir el nivel de respuesta (variable `Response`) obtenido en cada uno de los ítems de Likert. Concretamente, se compara el modelo que tenga como único predictor el nivel de subtitulado (`Treat`) con el modelo nulo (sin predictores) y también con el modelo en el que se han añadido los predictores `Period` y `Seq` para comprobar si hay significación estadística de la presencia de efectos periodo y secuencia respectivamente.\n\n#### Comprobación de las hipótesis del modelo $CM$\n\nEl modelo $CM$ presupone que los $odds$ entre dos niveles de respuesta son proporcionales para los mismos valores de variables explicativas. Como se vio en la @eq-ordinal2, es equivalente comprobar que los $odds$ son proporcionales que comprobar que la diferencia en `logits` es constante.\n\nNo existe un acuerdo generalmente aceptado sobre como comprobar la proporcionalidad de $odds$. Así, por ejemplo, el paquete `ordinal` [ver @ordinalR] dispone de la función `nominal_test()` que lo que hace es realizar un test de razón de verosimilitud para cada predictor ajustando un modelo en el que se ha relajado la condición de proporcionalidad. Otra posibilidad es utilizar el Test de Brant [ver @brant1990] que compara los coeficientes obtenidos con los que resultarían de ajustar cada nivel de respuesta mediante una Regresión Logística. Finalmente @harrell2015 [ver pp. 315-316] propone un método gráfico para verificar la hipótesis de proporcionalidad de $odds$. En este trabajo se ha preferido esta última técnica. Para ello se calcula la diferencia en `logits` acumulados entre dos niveles de respuesta consecutivos en cada valor de cada variable predictiva y se comprueba si las diferencias son similares. En la @fig-po.check se han calculado para los predictores `Treat`, `Period`, `Seq` y `Item` las diferencias de `logits` entre cada dos niveles consecutivos de respuesta. Se constata que las diferencias son pequeñas particularmente para el periodo y para la secuencia. También son moderadas para la mayoría de los ítems. La diferencia es mayor en el subtitulado en la comparación de los niveles de respuesta 1 y 2. Con esta evidencia, se acepta la hipótesis de proporcionalidad de $odds$. En la @tbl-po.check se muestra como se realiza el cálculo de la diferencia de $odds$ para el predictor `Seq` y así facilitar la comprensión de la construcción de la figura. En caso de que la proporcinalidad de $odds$ no se cumpla existen varias posibilidades. Una sería desechar el modelo ordinal y usar una Regresión Multinomial. Otra sería relajar la hipótesis de proporcionalidad de $odds$ estimando un coeficiente distinto para cada nivel de respuesta y nivel de factor. La función `vglm` del paquete `VGAM` [ver @VGAMR] permite hacer esto.\n\n\\clearpage\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Comprobación de la proporcionalidad de *odds*.](4_files/figure-pdf/fig-po.check-1.pdf){#fig-po.check}\n:::\n:::\n\n::: {#tbl-po.check .cell tbl-cap='Comprobación de la proporcionalidad de *odds* para Seq.'}\n::: {.cell-output-display}\n\\begin{longtable}{crrrrr}\n\\toprule\nResponse & n & cum.sum & odds & log.odds & diff.log.odds \\\\ \n\\midrule\n\\multicolumn{6}{l}{AB} \\\\ \n\\midrule\n1 & 89 & 89 & $0.06$ & $-2.74$ & $-1.38$ \\\\ \n2 & 210 & 299 & $0.26$ & $-1.36$ & $-0.68$ \\\\ \n3 & 192 & 491 & $0.50$ & $-0.69$ & $-1.05$ \\\\ \n4 & 375 & 866 & $1.44$ & $0.37$ & $-Inf$ \\\\ \n5 & 600 & 1466 & $Inf$ & $Inf$ & NA \\\\ \n\\midrule\n\\multicolumn{6}{l}{BA} \\\\ \n\\midrule\n1 & 78 & 78 & $0.05$ & $-2.91$ & $-1.44$ \\\\ \n2 & 204 & 282 & $0.23$ & $-1.47$ & $-0.69$ \\\\ \n3 & 191 & 473 & $0.45$ & $-0.79$ & $-1.62$ \\\\ \n4 & 582 & 1055 & $2.30$ & $0.83$ & $-Inf$ \\\\ \n5 & 459 & 1514 & $Inf$ & $Inf$ & NA \\\\ \n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\n#### Ajuste del modelo ordinal `Response ~ Treat`\n\nExisten varios paquetes en R que permiten ajustar un modelo $CM$ con función de enlace logística. El más popular es el paquete `ordinal` [ver @ordinalR]. El paquete `VGAM` [ver @VGAMR] es más flexible y potente. Otra posibilidad es usar la función `polr` del paquete `MASS` [ver @MASSR]. Finalmente la función `orm` del paquete `rms` también permite hacerlo [ver @harrell2015]. En este trabajo se usa el paquete `ordinal` [ver @ordinalR] por permitir también incluir efectos aleatorios que se utilizarán en el modelado multinivel. Se comienza con un modelo simple que tiene como único predictor el nivel de subtitulado por ser la variable más importante al ser el objeto de la pregunta de investigación:\n\n$$\n\\text{logit}(P(Response_i \\leq k)) = \\tau_k - \\beta_1 \\text{Treat}_i,\n$$\n\n\n\\scriptsize\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nclm_treat <-\n    clm(\n        Response ~ Treat,\n        data = df_response, link = \"logit\"\n    )\nsummary(clm_treat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nformula: Response ~ Treat\ndata:    df_response\n\n link  threshold nobs logLik   AIC     niter max.grad cond.H \n logit flexible  2980 -3966.11 7942.21 5(0)  1.64e-10 3.1e+01\n\nCoefficients:\n       Estimate Std. Error z value Pr(>|z|)    \nTreatB  -1.7206     0.0731  -23.54   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nThreshold coefficients:\n    Estimate Std. Error z value\n1|2 -3.97230    0.09678 -41.045\n2|3 -2.45446    0.06812 -36.029\n3|4 -1.66453    0.05936 -28.042\n4|5 -0.10547    0.04946  -2.132\n```\n:::\n:::\n\n\\normalsize\n\n\n::: {.cell}\n\n:::\n\n\nLa función `summary()` muestra la información resumen. Para su interpretación se va a seguir @christensen2018CumulativeLM. El número de condición Hessiano es inferior a $10^4$ lo que es indicativo de que no hay problemas de optimización\n^[El número de condición de Hessiano es una medida de la curvatura de una función en un punto.\nSi el número de condición de Hessiano es grande, la función es muy sensible a pequeñas perturbaciones y puede ser difícil de optimizar.]. La sección de coeficientes es la más importante: Se muestra la estimación de parámetros, el error estándar y la significación estadística de acuerdo al Test de Wald para el parámetro `TreatB`. Se comprueba que el valor es claramente significativo. Es decir, que los estudiantes han valorado de forma diferente la calidad del subtitulado en ambos vídeos. El estimador de maxima verosimilitud del coeficiente `TreatB` es -1.72. Siguiendo la deducción de @bruin2011 se puede, por ejemplo, hacer la siguiente interpretación del significado de este coeficiente referido a dos niveles consecutivos de respuesta, por ejemplo 1 y 2:\n\n$$\n\\begin{aligned}\nlogit [P(Y \\le 1)] & = & -3.97 - (-1.72 x_1) \\\\\nlogit [P(Y \\le 2)] & = & -2.45 - (-1.72 x_1)\n\\end{aligned}\n$$\n\nPor lo tanto y teniendo en cuenta que $x_1 = 1$ cuando $Treat = B$ y $x_1 = 0$ cuando $Treat = A$, se pueden calcular los $odds$ de $A$ y de $B$:\n\n$$\n\\begin{aligned}\n\\frac{P(Y \\le 1 \\mid x_1 = B)}{P(Y > 1 \\mid x_1 = B)} & = & exp(-3.97)/exp(-1.72) \\\\\n\\frac{P(Y \\le 1 \\mid x_1 = A)}{P(Y > 1 \\mid x_1 = A)} & = & exp(-3.97) \\\\\n\\frac{P(Y \\le 2 \\mid x_1 = B)}{P(Y > 2 \\mid x_1 = B)} & = & exp(-2.45)/exp(-1.72) \\\\\n\\frac{P(Y \\le 2 \\mid x_1 = A)}{P(Y > 2 \\mid x_1 = A)} & = & exp(-2.45)\n\\end{aligned}\n$$\n\nY los $OR$ del subtitulado $B$ sobre $A$ para los niveles de respuesta 1 y 2:\n\n$$\n\\begin{aligned}\n\\frac{P(Y \\le 1 | x_1=B)}{P(Y > 1 | x_1=B)} / \\frac{P(Y \\le 1 | x_1=A)}{P(Y > 1 | x_1=A)} & = & 1/exp(-1.72) & = & 5.59 \\\\\n\\frac{P(Y \\le 2 | x_1=B)}{P(Y > 2 | x_1=B)} / \\frac{P(Y \\le 2 | x_1=A)}{P(Y > 2 | x_1=A)} & = & 1/exp(-1.72) & = & 5.59 \\\\\n\\end{aligned}\n$$\n\nSe comprueba que el $OR$ es equivalente en todos los niveles de respuesta al cuestionario. Esta es la suposición principal de los modelos $CM$. El $odds$ de respuesta al cuestionario entre los niveles inferiores y superiores a uno dado, $k$, es 5.59 veces en el subtitulado $B$ que en el $A$. Esto indica que el subtitulado $B$ es percibido por los estudiantes como de peor calidad que el subtitulado $A$. Concretamente, el $OR$ de observar una mejor respuesta en un ítem del test es 5.59 veces superior en el nivel de subtitulado $A$ que en el $B$. Aunque no suele ser de interés, la interpretación de los coeficientes de los umbrales (`Threshold coefficients`), se pueden utilizar para estimar las probabilidades de respuesta. Por ejemplo, para el nivel de subtitulado $B$ y nivel de respuesta 2:\n\n$$\n\\begin{aligned}\nlogit [P(Y \\le 1)] & = & -3.97 - (-1.72) & = & -2.25 \\\\\nP(Y \\le 1) & = & \\frac{exp(-2.25)}{1 + exp(-2.25)} & = & 0.10 \\\\\nlogit [P(Y \\le 2)] & = & -2.45 - (-1.72) & = & -0.73 \\\\\nP(Y \\le 2) & = & \\frac{exp(-0.73)}{1 + exp(-0.73)} & = & 0.32 \\\\\nP(Y = 2) & = & P(Y \\le 2) - P(Y \\le 1) & = &  0.23 \n\\end{aligned}\n$$\n\nPara el subtitulado $A$ no se tiene en cuenta el coeficiente $TreatB$ ya que el valor $x_1$ es cero:\n\n$$\n\\begin{aligned}\nlogit [P(Y \\le 1)] & = & & & -3.97 \\\\\nP(Y \\le 1) & = & \\frac{exp(-3.97)}{1 + exp(-3.97)} & = & 0.02 \\\\\nlogit [P(Y \\le 2)] & = & & & -2.45 \\\\\nP(Y \\le 2) & = & \\frac{exp(-2.45)}{1 + exp(-2.45)} & = & 0.08 \\\\\nP(Y = 2) & = & P(Y \\le 2) - P(Y \\le 1) & = &  0.06 \n\\end{aligned}\n$$\n\nEn @tbl-probs-clm-treat se muestran las probabilidades para ambos niveles de subtitulado y todos los posibles valores de respuesta. Se confirma que en el nivel de subtitulado $A$ son más probables las respuestas 5 y 4, siendo poco probables el resto de niveles. Sin embargo, en el subtitulado $B$ existe bastante incertidumbre, siendo el valor más probable el nivel 4 y muy similares los niveles 2, 3 y 5. Esto se corresponde con lo que ya se había constatado en el Análisis Exploratorio (ver @fig-freqs). Se debe tener en cuenta que este modelo tiene un único predictor y, por lo tanto, no es capaz de explicar las diferencias en el nivel de respuesta para distintos periodos, secuencias, ítems o estudiantes. En las siguientes secciones se investiga si en el nivel de respuesta influyen estos predictores.\n\n\n::: {#tbl-probs-clm-treat .cell tbl-cap='Probabilidades de respuesta para el modelo ordinal Response ~ Treat' tbl-scap='Probabilidades de respuesta para el modelo ordinal con un predictor.'}\n::: {.cell-output-display}\n\\begin{tabular}{l|r|r|r|r|r}\n\\hline\n  & 1 & 2 & 3 & 4 & 5\\\\\n\\hline\nA & 0.018 & 0.061 & 0.08 & 0.315 & 0.526\\\\\n\\hline\nB & 0.095 & 0.229 & 0.19 & 0.320 & 0.166\\\\\n\\hline\n\\end{tabular}\n:::\n:::\n\n\n#### Ajuste del modelo ordinal `Response ~ Treat * Period` {#sec-response-treat.period}\n\nPara saber si existe un efecto periodo, se añade como predictor la variable `Period`. También se añade la interacción entre subtitulado y periodo\n^[Se debe tener en cuenta que en R la interacción entre dos variables se puede añadir con los símbolos \"$*$\" y \"$:$\". El símbolo \"$*$\" añade al modelo tanto los efectos principales como la interacción, mientras que el símbolo \"$:$\" tan solo añade la interacción. Por ello, los modelos $Response \\sim Treat*Period$ y $Response \\sim Treat + Period + Treat:Period$ son equivalentes en R]:\n\n\\small\n\n$$\n\\text{logit}(P(Response_i \\leq k)) = \\tau_k - \\beta_1 \\text{Treat}_i - \\beta_2 \\text{Period}_i - \\beta_3 \\text{Treat}_i : \\text{Period}_i\n$$ {#eq-ordinal-3}\n\n\\normalsize\n\nEn el @sec-contrasts se demuestra que cuando el contraste es $sum$ la interacción entre periodo y subtitulado es equivalente al \\gls{efecto secuencia}. Es decir, que los modelos `Response ~ Treat*Period` y `Response ~ Treat + Period + Seq` son equivalentes. Esto no sucede cuando el contraste es $treatment$, que es el utilizado por defecto en R. En la @tbl-contrast se comparan los coeficientes de los cuatro modelos que se listan a continuación:\n\n* `Response ~ Treat * Period` con contraste `treatment`.\n* `Response ~ Treat + Period + Seq` con contraste `treatment`.\n* `Response ~ Treat * Period` con contraste `sum`.\n* `Response ~ Treat + Period + Seq` con contraste `sum`.\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\\tiny\n\n::: {#tbl-contrast .cell tbl-cap='Comparación de los coeficientes con contraste \"treatment\" y \"sum\".' tbl-width='8'}\n::: {.cell-output-display}\n\\begin{longtable}{lrlrlrlr}\n\\toprule\n\\multicolumn{4}{c}{contr.treatment} & \\multicolumn{4}{c}{contr.sum} \\\\ \n\\cmidrule(lr){1-4} \\cmidrule(lr){5-8}\n\\multicolumn{2}{c}{Response \\textasciitilde{} Treat*Period} & \\multicolumn{2}{c}{Response \\textasciitilde{} Treat+Period+Seq} & \\multicolumn{2}{c}{Response \\textasciitilde{} Treat*Period} & \\multicolumn{2}{c}{Response \\textasciitilde{} Treat+Period+Seq} \\\\ \n\\cmidrule(lr){1-2} \\cmidrule(lr){3-4} \\cmidrule(lr){5-6} \\cmidrule(lr){7-8}\ncoef & value & coef & value & coef & value & coef & value \\\\ \n\\midrule\n1|2 & $-4.246$ & 1|2 & $-4.246$ & 1|2 & $-3.127$ & 1|2 & $-3.127$ \\\\ \n2|3 & $-2.728$ & 2|3 & $-2.728$ & 2|3 & $-1.608$ & 2|3 & $-1.608$ \\\\ \n3|4 & $-1.938$ & 3|4 & $-1.938$ & 3|4 & $-0.818$ & 3|4 & $-0.818$ \\\\ \n4|5 & $-0.370$ & 4|5 & $-0.370$ & 4|5 & $0.750$ & 4|5 & $0.750$ \\\\ \nTreatB & $-1.960$ & TreatB & $-1.748$ & Treat1 & $0.874$ & Treat1 & $0.874$ \\\\ \nPeriod2 & $-0.492$ & Period2 & $-0.279$ & Period1 & $0.140$ & Period1 & $0.140$ \\\\ \nTreatB:Period2 & $0.425$ & SeqBA & $-0.213$ & Treat1:Period1 & $0.106$ & Seq1 & $0.106$ \\\\ \n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\\normalsize\n\nSe comprueba que coinciden los coeficientes de los dos modelos con contraste `sum` y que el efecto secuencia es equivalente a la interacción de periodo y subtitulado con este contraste. Sin embargo, en el contraste `treatment` coinciden los coeficientes de los interceptores pero no así los de los factores. Además, estos tres últimos coeficientes tienen nombres diferentes en los dos contrastes. La diferencia en el nombre se corresponde con la distinta interpretación del significado de los coeficientes. En el contraste `treatment` los valores de los interceptos se refieren a los valores de los factores en el nivel de referencia de cada factor (en este caso $Treat = A$ y $Period = 1$) y los valores de los otros coeficientes ($TreatB$ y $Period2$) son la diferencia con el de referencia. Así, por ejemplo, $TreatB$ es la diferencia con $TreatA$ en el periodo 1. Con este tipo de contraste es más difícil aislar el efecto que produce un nivel de un factor independiente del otro factor. En el contraste `sum` los valores de los interceptos son el efecto medio\n^[Se calcula como la media de las medias de cada combinación de los niveles de factor.], y los coeficientes $Treat1$ y $Period1$ son los efectos que sobre ese valor medio produce el nivel de factor de referencia, que en este caso es el primero ($Treat = A$ y $Period = 1$ respectivamente). Así por ejemplo en el contraste `sum`:\n\n* El coeficiente $1|2$ tiene un valor -3.127 y es el `logit` medio de que la respuesta sea menor que 1 frente a que sea mayor que 1.\n* El coeficiente $Treat1$ tiene un valor de 0.874 y es la diferencia en `logits` que se añade en el nivel de subtitulado $A$ sin tener en cuenta el periodo. Es decir, que es el efecto del subtitulado $A$. Su valor es positivo. Como en la @eq-ordinal-3 aparece restando, el subtitulado $A$ hace más pequeño el `logit` y, por lo tanto, disminuye la probabilidad de una respuesta inferior frente a una superior. \n* Para obtener el efecto del subtitulado $B$ se cambia el signo a $Treat1$: -0.874. Por ello aumenta la probabilidad de un menor valor de respuesta.\n* La diferencia en `logits` de los efectos totales del subtitulado es el doble de 0.874.\n* El coeficiente $Period1$ tiene un valor 0.14 y es la diferencia en `logits` que produce el periodo $1$ sin tener en cuenta el subtitulado. \n* El efecto del periodo $2$ se obtiene cambiado el signo al efecto del periodo 1: -0.14.\n* El efecto total del periodo es 0.279 `logits`.\n* El coeficiente $Treat1:Period1$ tiene un valor de 0.106 y es la interacción entre el subtitulado $A$ y el periodo $1$. Es equivalente al efecto en `logits` de la secuencia $AB$. El efecto de la secuencia $BA$ será  -0.106.\n* Por lo tanto el efecto total en `logits` del subtitulado $A$ en el periodo 1 será $1|2 - Treat1 - Period1 - Treat1:Period1 = -3.127 - 0.874 - 0.14 - 0.106 = -4.246$. Obsérvese que este valor corresponde con el parámetro $1|2$ de los modelos con contraste `treatment`.\n* El efecto total en `logits` del subtitulado $B$ en el periodo 1 será $1|2 + Treat1 - Period1 + Treat1:Period1 = -3.127 + 0.874 - 0.14 + 0.106$.\n* El efecto total en `logits` del subtitulado $A$ en el periodo 2 será $1|2 - Treat1 + Period1 + Treat1:Period1 = -3.127 - 0.874 + 0.14 + 0.106$.\n* El efecto total en `logits` del subtitulado $B$ en el periodo 2 será $1|2 + Treat1 + Period1 - Treat1:Period1 = -3.127 + 0.874 + 0.14 - 0.106$.\n\nEn la @tbl-contrat2 se muestra la equivalencia de los coeficientes entre los modelos ajustados con cada contraste. La conclusión que se obtiene de todo esto es que cuando se usan dos o más factores, la interpretación con contraste `sum` resulta más intuitiva y sencilla y será el contraste utilizado en este trabajo.\n\n\\small\n\n| contr.treatment | contr.sum                               | value   |\n|-----------------|-----------------------------------------|---------|\n| 1\\|2            | 1\\|2 - Treat1 - Period1 - Treat1:Period1 | -4.246 |\n| 2\\|3            | 2\\|3 - Treat1 - Period1 - Treat1:Period1 | -2.728 |\n| 3\\|4            | 3\\|4 - Treat1 - Period1 - Treat1:Period1 | -1.938 |\n| 4\\|5            | 4\\|5 - Treat1 - Period1 - Treat1:Period1 | -0.37 |\n| TreatB          | -2(Treat1 + Treat1:Period1)             | -1.96 |\n| Period2          | -2(Period1 + Treat1:Period1)             | -0.492 |\n| TreatB:Period2          | 4(Treat1:Period1)             | 0.425 |\n\n: Equivalencia entre los coeficientes `contr.treatment` y `contr.sum` en el modelo Response ~ Treat*Period.  {#tbl-contrat2}\n\n\\normalsize\n\n\nA continuación se muestra el resumen del modelo con contraste `sum` para constatar que los tres coeficientes son significativos:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\nformula: Response ~ Treat * Period\ndata:    df_response\n\n link  threshold nobs logLik   AIC     niter max.grad cond.H \n logit flexible  2980 -3953.01 7920.03 5(0)  2.13e-10 1.4e+01\n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \nTreat1          0.87395    0.03678  23.763  < 2e-16 ***\nPeriod1         0.13962    0.03411   4.094 4.25e-05 ***\nTreat1:Period1  0.10627    0.03410   3.117  0.00183 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nThreshold coefficients:\n    Estimate Std. Error z value\n1|2 -3.12665    0.08242  -37.94\n2|3 -1.60838    0.04968  -32.38\n3|4 -0.81849    0.04225  -19.37\n4|5  0.74993    0.04194   17.88\n```\n:::\n:::\n\n\n#### Elección del modelo ordinal mediante el test de razón de verosimilitud {#sec-mejor-modelo-efectos-fijos}\n\nLa @tbl-ordinal-com compara tres modelos ordinales con el contraste $sum$:\n\n* Modelo nulo.\n* Modelo con predictor `Treat`.\n* Modelo con predictores `Treat` y `Period` y su interacción (que es equivalente a incluir el predictor `Seq`).\n\nSe constata que los coeficientes estimados en los tres modelos son significativos y de similar valor.\n\n\\scriptsize\n\n::: {#tbl-ordinal-com .cell tbl-cap='Comparación de modelos ordinales.'}\n::: {.cell-output-display}\n\\begin{longtable}{lcccccc}\n\\toprule\n & \\multicolumn{2}{c}{Response \\textasciitilde{} 1    } & \\multicolumn{2}{c}{Response \\textasciitilde{} Treat    } & \\multicolumn{2}{c}{Response \\textasciitilde{} Treat:Period    } \\\\ \n\\cmidrule(lr){2-3} \\cmidrule(lr){4-5} \\cmidrule(lr){6-7}\n  & Est. & S.E. & Est.  & S.E.  & Est.   & S.E.   \\\\ \n\\midrule\n1|2  & -2.824*** & 0.080 & -3.112*** & 0.082 & -3.127*** & 0.082 \\\\ \n2|3  & -1.418*** & 0.046 & -1.594*** & 0.049 & -1.608*** & 0.050 \\\\ \n3|4  & -0.738*** & 0.039 & -0.804*** & 0.042 & -0.818*** & 0.042 \\\\ \n4|5  & 0.596*** & 0.038 & 0.755*** & 0.042 & 0.750*** & 0.042 \\\\ \nTreat1  &  &  & 0.860*** & 0.037 & 0.874*** & 0.037 \\\\ \nPeriod1  &  &  &  &  & 0.140*** & 0.034 \\\\ \nTreat1 × Period1  &  &  &  &  & 0.106** & 0.034 \\\\ \nNum.Obs. & 2980 &  & 2980 &  & 2980 &  \\\\ \nAIC & 8541.7 &  & 7942.2 &  & 7920.0 &  \\\\ \nBIC & 8565.7 &  & 7972.2 &  & 7962.0 &  \\\\ \nLog.Lik. & -4266.851 &  & -3966.107 &  & -3953.013 &  \\\\ \nedf & 4 &  & 5 &  & 7 &  \\\\ \n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\\normalsize\n\nAl ser los tres modelos anidados se pueden comparar con la prueba de razón de verosimilitud. Se comprueba que el tercer modelo reduce significativamente el logaritmo de la función de verosimilitud y, por lo tanto, debe ser aceptado:\n\n\\scriptsize\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio tests of cumulative link models:\n \n                     formula:                  link: threshold:\nclm_sum_null         Response ~ 1              logit flexible  \nclm_sum_treat        Response ~ Treat          logit flexible  \nclm_sum_treat.period Response ~ Treat * Period logit flexible  \n\n                     no.par    AIC  logLik LR.stat df Pr(>Chisq)    \nclm_sum_null              4 8541.7 -4266.9                          \nclm_sum_treat             5 7942.2 -3966.1 601.490  1  < 2.2e-16 ***\nclm_sum_treat.period      7 7920.0 -3953.0  26.186  2  2.059e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\\normalsize\n\nEste modelo estima coeficientes positivos para `Treat1`, `Period1` y `Treat1:Period1` (equivalente a `Seq1`). Estos coeficientes indican que:\n\n* Son más probables mayores niveles de respuesta en el subtitulado $A$ que en el $B$.\n* Son más probables mayores niveles de respuesta en el periodo 1 que en el 2.\n* Son más probables mayores niveles de respuesta en la secuencia $AB$ que en la secuencia $BA$.\n* No obstante, y a pesar de que el efecto periodo y el efecto secuencia son significativos, el efecto del nivel de subtitulado medido en `logits` es ocho veces más importante que estos efectos considerados individualmente y cuatro veces considerados de forma conjunta.\n\n \n### Regresión Ordinal Multinivel {#sec-multinivel-2}\n\nEn la @sec-multinivel se expuso el fundamento teórico de los modelos multinivel. Aquí se justifica su interés aplicado al caso del subtitulado de vídeos. Hay dos variables susceptibles de ser incorporadas al modelo como efectos aleatorios. El primer candidato es el factor `Subject`. Es evidente que los estudiantes son una muestra de una población más amplia que estaría constituida por todos los estudiantes del curso de \\gls{accesibilidad}. Pero es que además cada estudiante responde a cada ítem dos veces y, por lo tanto, sus observaciones no son independientes. En la @fig-subjects se muestran las respuestas de diez estudiantes a cada subtitulado. Se observa que las respuestas no son independientes ya que cada estudiante tiene un preferencia por uno o varios niveles de respuesta en cada test. Por otro lado, los ítems no son independientes unos de otros ya que pretenden medir la misma variable subyacente. Además, el interés no es conocer el valor concreto de sus coeficientes sino su valor en relación a los coeficientes de los otros ítems. En @burkner2021 [pp. 14-16] y en @burkner2019 [pp. 19-20] se puede encontrar un ejemplo con esta parametrización aplicada a una \\gls{escala de likert}.\n\n#### Modelo Response ~ Treat * Period + (1 | Subject)\n\nEl primer modelo que se propone es un modelo que mantiene los predictores `Treat` y `Period` y su interacción (equivalente al \\gls{efecto secuencia}) como efectos fijos que fueron seleccionadas en la sección anterior (ver @sec-mejor-modelo-efectos-fijos) e incorpora los estudiantes como efectos aleatorios sobre los interceptos:\n\n\\small\n\n\n$$\n\\begin{aligned}\nNivel\\ 1: & \\text{logit}(P(Response_{ij} \\leq k)) = \\tau_{kj} - \\beta_1 \\text{Treat}_{ij} - \\beta_2 \\text{Period}_{ij} - \\beta_3 \\text{Treat}_{ij} : \\text{Period}_{ij} \\\\\nNivel\\ 2: & \\tau_{kj}  =  \\tau_{k} + Subject_{0j}\n\\end{aligned}\n$$\n\n\\normalsize\n\ndonde $ij$ es la observación $i$ del estudiante $j$. Obsérvese que ahora los interceptos $\\tau_{kj}$ se descomponen en una parte fija y común para cada nivel de respuesta $k$, $\\tau_{k}$ y una parte variable específica para cada estudiante $Subject_{0j}$. Para ajustar el modelo se va a utilizar la función `clmm` del paquete `ordinal` [ver @ordinalR] ya que permite la inclusión de efectos aleatorios. \n\n\\scriptsize\n\n::: {.cell}\n::: {.cell-output-display}\n![Respuestas de los estudiantes por nivel de subtitulado.](4_files/figure-pdf/fig-subjects-1.pdf){#fig-subjects}\n:::\n:::\n\n\\normalsize\n\n\n\\scriptsize\n\n::: {.cell hash='4_cache/pdf/unnamed-chunk-37_a361dbf55423eea6b93ef080deaa846f'}\n\n```{.r .cell-code}\noptions(contrasts = rep(\"contr.sum\", 2))\nclmm_treat.period_subject <- clmm(\n    Response ~ Treat * Period + (1 | Subject),\n    data = df_response\n)\nsummary(clmm_treat.period_subject)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCumulative Link Mixed Model fitted with the Laplace approximation\n\nformula: Response ~ Treat * Period + (1 | Subject)\ndata:    df_response\n\n link  threshold nobs logLik   AIC     niter     max.grad cond.H \n logit flexible  2980 -3655.71 7327.41 765(3046) 1.63e-03 8.1e+01\n\nRandom effects:\n Groups  Name        Variance Std.Dev.\n Subject (Intercept) 1.278    1.131   \nNumber of groups:  Subject 87 \n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \nTreat1          1.05368    0.03999  26.346  < 2e-16 ***\nPeriod1         0.15662    0.03604   4.346 1.39e-05 ***\nTreat1:Period1  0.14262    0.12677   1.125    0.261    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nThreshold coefficients:\n    Estimate Std. Error z value\n1|2  -3.7046     0.1523 -24.332\n2|3  -2.0298     0.1349 -15.050\n3|4  -1.1012     0.1310  -8.406\n4|5   0.8281     0.1299   6.375\n```\n:::\n:::\n\n\\normalsize\n\nEn la parte de efectos fijos: los interceptos tienen valores similares al modelo de efectos fijos (ver @sec-response-treat.period) aunque los coeficientes incrementan ligeramente su valor. Esto indica una mayor distancia entre las respuestas de los subtitulados $A$ y $B$. En este modelo el efecto secuencia no es significativo. En cuanto a los efectos aleatorios: la varianza del intercepto aleatorio de los estudiantes es 1.28. En la @fig-random-subject-var se muestran los valores de los interceptos estimados de los estudiantes. La media de estos interceptos como se espera es cercana a cero (-0.008).\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribución de interceptos aleatorios por estudiante en el modelo Response ~ Treat * Period + (1 | Subject)](4_files/figure-pdf/fig-random-subject-var-1.pdf){#fig-random-subject-var fig-scap='Distribución de interceptos aleatorios por estudiante.'}\n:::\n:::\n\n\n#### Modelo Response ~ Treat * Period + (1 + Treat | Subject)\n\nEs posible que cada estudiante valore con diferente criterio cada subtitulado. Para estimarlo, se propone el siguiente modelo:\n\n\n\\small\n\n\n$$\n\\begin{aligned}\nNivel\\ 1: & \\text{logit}(P(Response_{ij} \\leq k)) = \\tau_{kj} - \\beta_{1j} \\text{Treat}_{ij} - \\beta_{2} \\text{Period}_{ij} - \\beta_{3} \\text{Treat}_{ij} * \\text{Period}_{ij} \\\\\nNivel\\ 2: & \\tau_{kj}  =  \\tau_{k} + Subject_{0j} \\\\\n          & \\beta_{1j}  =  \\beta_{1} + Subject_{1j}\n\\end{aligned}\n$$\n\n\\normalsize\n\n\nAhora el parámetro $\\beta_{1j}$ del subtitulado tiene dos componentes: Uno común a todos los niveles de respuesta $\\beta_{1}$ y otro particular de cada estudiante $Subject_{1j}$. El modelo ajustado ocasiona que solo `Treat1` sea significativo, ya que ni el periodo ni la secuencia lo son. En los efectos aleatorios la correlación entre intercepto y pendiente es prácticamente nula.\n\n\\scriptsize\n\n::: {.cell hash='4_cache/pdf/unnamed-chunk-39_75a1fec5172f0e072d2206e774ce02bc'}\n\n```{.r .cell-code}\noptions(contrasts = rep(\"contr.sum\", 2))\nclmm_treat.period_treat.subject <- clmm(\n    Response ~ Treat * Period + (1 + Treat | Subject),\n    data = df_response\n)\nsummary(clmm_treat.period_treat.subject)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCumulative Link Mixed Model fitted with the Laplace approximation\n\nformula: Response ~ Treat * Period + (1 + Treat | Subject)\ndata:    df_response\n\n link  threshold nobs logLik   AIC     niter     max.grad cond.H \n logit flexible  2980 -3429.88 6879.76 905(6264) 1.33e-03 8.2e+01\n\nRandom effects:\n Groups  Name        Variance Std.Dev. Corr   \n Subject (Intercept) 1.712    1.308           \n         Treat1      1.042    1.021    -0.062 \nNumber of groups:  Subject 87 \n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \nTreat1           1.2938     0.1197  10.809   <2e-16 ***\nPeriod1          0.1620     0.1171   1.383    0.167    \nTreat1:Period1   0.1327     0.1464   0.906    0.365    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nThreshold coefficients:\n    Estimate Std. Error z value\n1|2  -4.2633     0.1761 -24.210\n2|3  -2.3321     0.1562 -14.932\n3|4  -1.2656     0.1520  -8.324\n4|5   0.9659     0.1509   6.400\n```\n:::\n:::\n\n\\normalsize\n\n#### Comparación de modelos\n\nSe pueden comparar los modelos con el test de razón de verosimilitud que se realiza con la función `anova` del paquete `ordinal` [ver @ordinalR]. Se comprueba que en este test resulta significativamente mejor el último modelo:\n\n\\scriptsize\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(clmm_treat.period_subject, clmm_treat.period_treat.subject)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLikelihood ratio tests of cumulative link models:\n \n                                formula:                                         \nclmm_treat.period_subject       Response ~ Treat * Period + (1 | Subject)        \nclmm_treat.period_treat.subject Response ~ Treat * Period + (1 + Treat | Subject)\n                                link: threshold:\nclmm_treat.period_subject       logit flexible  \nclmm_treat.period_treat.subject logit flexible  \n\n                                no.par    AIC  logLik LR.stat df Pr(>Chisq)    \nclmm_treat.period_subject            8 7327.4 -3655.7                          \nclmm_treat.period_treat.subject     10 6879.8 -3429.9  451.66  2  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\\normalsize\n\n#### Elección del mejor modelo\n\nEn el apartado anterior se introdujo a los estudiantes como efecto aleatorio.\nComo se ha dicho, los ítems también pueden modelizarse como aleatorios.\nEsto produce una multiplicidad de modelos.\nLos siguientes son los que se han comparado:\n\n* Response ~ (1 | Subject)\n* Response ~ (1 + Treat | Subject)\n* Response ~ (1 + Treat | Item)\n* Response ~ Treat + (1 + Treat | Subject)\n* Response ~ Treat + (1 + Treat | Item)\n* Response ~ Treat*Period + (1 + Treat  | Subject)\n* Response ~ Treat*Period + (1 + Treat  | Item)\n* Response ~ Treat*Period + (1 + Period | Subject) + (1 + Treat | Item)\n* Response ~ Treat + (1 + Treat | Subject) + (1 + Treat | Item)\n* Response ~ Treat*Period + (1 + Treat  | Subject) + (1 + Treat | Item)\n\nEl último de ellos produce un resultado significativo en el test de razón de verosimilitud con todos los demás. Sin embargo los parámetros de todos los modelos tienen valores similares por lo que no cambia la interpretación que se haga de ellos en cada modelo. Este modelo tiene un $AIC$ menor que los modelos ordinales ajustados en el apartado anterior (ver @sec-ordinal-2) incluso si a esos modelos se les añade como factor predictor `Item`. Será este, por lo tanto, el modelo seleccionado.\n\n\n\nLa @eq-mejor-modelo del modelo seleccionado es la siguiente:\n\n\\small\n\n\n$$\n\\begin{aligned}\nNivel\\ 1: & \\text{logit}(P(Response_{ijl} \\leq k)) = \\tau_{kjl} - \\beta_{1jl} \\text{Treat}_{ijl} - \\beta_{2} \\text{Period}_{ijl} - \\beta_{3} \\text{Treat}_{ijl} : \\text{Period}_{ijl} \\\\\nNivel\\ 2: & \\tau_{kjl}  =  \\tau_{k} + Subject_{0j} + Item_{0l} \\\\\n          & \\beta_{1jl}  =  \\beta_{1} + Subject_{1j} + Item_{1l}\n\\end{aligned}\n$$ {#eq-mejor-modelo}\n\n\\normalsize\n\ndonde $ijl$ se corresponde con la observación $i$-ésima del estudiante $j$ e ítem $l$. Ahora los interceptos y el coeficiente del subtitulado se componen de tres sumandos: una parte fija, una parte que depende del estudiante y una parte que depende del ítem de Likert. \n\n\nEl resumen de parámetros del modelo ajustado es el siguiente:\n\n\\scriptsize\n\n::: {.cell hash='4_cache/pdf/unnamed-chunk-41_8767592008d2234aa021365cbf7a607a'}\n\n```{.r .cell-code}\noptions(contrasts = rep(\"contr.sum\", 2))\nclmm_treat.period.subject.item <- clmm(\n    Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Item),\n    data = df_response\n)\n\nsummary(clmm_treat.period.subject.item)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCumulative Link Mixed Model fitted with the Laplace approximation\n\nformula: Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat |  \n    Item)\ndata:    df_response\n\n link  threshold nobs logLik   AIC     niter       max.grad cond.H \n logit flexible  2980 -3186.06 6398.11 1468(12273) 2.37e-03 1.5e+02\n\nRandom effects:\n Groups  Name        Variance Std.Dev. Corr   \n Subject (Intercept) 2.2176   1.4892          \n         Treat1      1.3650   1.1683   -0.128 \n Item    (Intercept) 0.4831   0.6950          \n         Treat1      0.4655   0.6823   -0.528 \nNumber of groups:  Subject 87,  Item 18 \n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \nTreat1           1.4320     0.2102   6.811  9.7e-12 ***\nPeriod1          0.1730     0.1325   1.306    0.192    \nTreat1:Period1   0.1397     0.1654   0.845    0.398    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nThreshold coefficients:\n    Estimate Std. Error z value\n1|2  -5.0033     0.2619 -19.104\n2|3  -2.6499     0.2417 -10.962\n3|4  -1.3659     0.2376  -5.748\n4|5   1.1837     0.2365   5.006\n```\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\\normalsize\n\nCon este modelo los efectos secuencia y periodo no son significativos. En cualquier caso, se mantienen ya que el test de razón de verosimilitud resulta significativo en este modelo respecto al modelo sin estos predictores.\n\n \n### Modelado bayesiano {#sec-bayesiano-2}\n\nExisten muchos paquetes en R para hacer inferencia bayesiana. Algunos de los más populares son:\n\n* OpenBUGS y WinBUGS: basado en el muestreo de Gibbs.\n* JAGS: también utiliza el muestreo de Gibbs.\n* Stan: Más moderno y con una comunidad de desarrollo más activa que los anteriores. Utiliza muestreo HMC (Hamiltonian Monte Carlo) y NUTS (no U-turn sampler). Stan tiene un lenguaje similar a C para definir modelos aunque hay muchos paquetes basados en Stan que facilitan la especificación de modelos con una sintaxis más sencilla. En este trabajo se utilizará uno de ellos, `brms` [ver @brms] . La sintaxis de especificación de modelos con este paquete es idéntica a la que se ha utilizado en la sección anterior.\n* INLA: Evita la simulación *\\gls{MCMC}* haciendo más rápida la convergencia. Es menos flexible ya que solo se pueden especificar modelos de la familia exponencial.\n\nSe han comparado múltiples modelos usando la función `LOO` que realiza una validación cruzada bayesiana `leave-one-out` similar a la que se explicó en la @sec-bayesiano. El mejor modelo ha resultado ser el mismo que se seleccionó en modelos mixtos (ver @eq-mejor-modelo). Es decir:\n\n\\small\n> Response ~ Treat*Period + (1 + Treat  | Subject) + (1 + Treat | Item)\n\\normalsize\n\n\\scriptsize\n\n::: {.cell hash='4_cache/pdf/unnamed-chunk-43_3898d2bfa861b7143db163ea8025faca'}\n\n```{.r .cell-code}\noptions(contrasts = rep(\"contr.sum\", 2))\nbrm_treat.period.subject.item <- brm(\n    Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Item),\n    data = df_response,\n    family = cumulative(\"logit\"),\n    iter = 4000,\n    sample_prior = TRUE,\n    file = \"models/brm_treat.period.subject.item\",\n    file_refit = \"on_change\"\n)\n```\n:::\n\n\\normalsize\n\nEl modelo utiliza como factores con efectos fijos (`complete pooling` en terminología bayesiana) el nivel de subtitulado y el periodo y la interacción entre ambos; y como efectos aleatorios (`partial pooling`) los sujetos y los ítems del test, cada uno de ellos con un intercepto y un nivel de subtitulado variable. El resumen del modelo es el siguiente:\n\n\\tiny\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(brm_treat.period.subject.item)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Family: cumulative \n  Links: mu = logit; disc = identity \nFormula: Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Item) \n   Data: df_response (Number of observations: 2980) \n  Draws: 4 chains, each with iter = 4000; warmup = 2000; thin = 1;\n         total post-warmup draws = 8000\n\nGroup-Level Effects: \n~Item (Number of levels: 18) \n                      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS\nsd(Intercept)             0.77      0.16     0.53     1.15 1.00     1468\nsd(Treat1)                0.77      0.15     0.53     1.12 1.00     1935\ncor(Intercept,Treat1)    -0.46      0.20    -0.78     0.01 1.00     1421\n                      Tail_ESS\nsd(Intercept)             2605\nsd(Treat1)                3580\ncor(Intercept,Treat1)     2555\n\n~Subject (Number of levels: 87) \n                      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS\nsd(Intercept)             1.54      0.14     1.29     1.85 1.00     1484\nsd(Treat1)                1.21      0.11     1.01     1.45 1.00     1519\ncor(Intercept,Treat1)    -0.11      0.12    -0.34     0.14 1.00     1228\n                      Tail_ESS\nsd(Intercept)             2741\nsd(Treat1)                3081\ncor(Intercept,Treat1)     2475\n\nPopulation-Level Effects: \n               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept[1]      -4.95      0.28    -5.52    -4.42 1.00      785     1753\nIntercept[2]      -2.59      0.26    -3.11    -2.09 1.01      743     1636\nIntercept[3]      -1.30      0.26    -1.82    -0.82 1.01      726     1532\nIntercept[4]       1.25      0.26     0.74     1.75 1.00      745     1571\nTreat1             1.46      0.23     1.01     1.92 1.00     1046     2071\nPeriod1            0.17      0.14    -0.09     0.44 1.00      848     1714\nTreat1:Period1     0.14      0.17    -0.20     0.47 1.01      686     1127\n\nFamily Specific Parameters: \n     Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\ndisc     1.00      0.00     1.00     1.00   NA       NA       NA\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n:::\n:::\n\n\\normalsize\n\n\nSe han mantenido las distribuciones de probabilidad a priori que por defecto utiliza `brm` confiando en que sus parámetros son adecuados. Sin embargo, conviene comprobar que realmente sea así. En la @tbl-priors se muestran las distribuciones a priori de los parámetros aleatorios del modelo. En la @fig-priors se constata que toman valores razonables y no informativos.\n\n\\tiny\n\n::: {#tbl-priors .cell tbl-cap='Distribuciones a priori del modelo ordinal seleccionado.' tbl-scap='Distribuciones a priori del modelo Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Item).'}\n::: {.cell-output-display}\n\\begin{longtable}{llllrrrrrl}\n\\toprule\nprior & class & coef & group & resp & dpar & nlpar & lb & ub & source \\\\ \n\\midrule\n & b &  &  &  &  &  &  &  & default \\\\ \n & b & Period1 &  &  &  &  &  &  & default \\\\ \n & b & Treat1 &  &  &  &  &  &  & default \\\\ \n & b & Treat1:Period1 &  &  &  &  &  &  & default \\\\ \nstudent\\_t(3, 0, 2.5) & Intercept &  &  &  &  &  &  &  & default \\\\ \nstudent\\_t(3, 0, 2.5) & Intercept & 1 &  &  &  &  &  &  & default \\\\ \nstudent\\_t(3, 0, 2.5) & Intercept & 2 &  &  &  &  &  &  & default \\\\ \nstudent\\_t(3, 0, 2.5) & Intercept & 3 &  &  &  &  &  &  & default \\\\ \nstudent\\_t(3, 0, 2.5) & Intercept & 4 &  &  &  &  &  &  & default \\\\ \nlkj\\_corr\\_cholesky(1) & L &  &  &  &  &  &  &  & default \\\\ \nlkj\\_corr\\_cholesky(1) & L &  & Item &  &  &  &  &  & default \\\\ \nlkj\\_corr\\_cholesky(1) & L &  & Subject &  &  &  &  &  & default \\\\ \nstudent\\_t(3, 0, 2.5) & sd &  &  &  &  &  & 0 &  & default \\\\ \nstudent\\_t(3, 0, 2.5) & sd &  & Item &  &  &  &  &  & default \\\\ \nstudent\\_t(3, 0, 2.5) & sd & Intercept & Item &  &  &  &  &  & default \\\\ \nstudent\\_t(3, 0, 2.5) & sd & Treat1 & Item &  &  &  &  &  & default \\\\ \nstudent\\_t(3, 0, 2.5) & sd &  & Subject &  &  &  &  &  & default \\\\ \nstudent\\_t(3, 0, 2.5) & sd & Intercept & Subject &  &  &  &  &  & default \\\\ \nstudent\\_t(3, 0, 2.5) & sd & Treat1 & Subject &  &  &  &  &  & default \\\\ \n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\\normalsize\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribuciones a priori del modelo Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Item).](4_files/figure-pdf/fig-priors-1.pdf){#fig-priors fig-scap='Distribuciones a priori del modelo seleccionado.'}\n:::\n:::\n\n\nEs importante asegurar que el entrenamiento ha convergido a su distribución a posteriori. En la tabla de resumen se constata que el valor de `Rhat`\n^[`Rhat` es una medida utilizada para evaluar la convergencia de las Cadenas de Markov Monte Carlo ($MCMC$) en el muestreo bayesiano. Compara la varianza de cada cadena individual de $MCMC$ con la varianza entre diferentes cadenas. Si las cadenas convergen, se espera que sus valores sean similares y, por lo tanto, el valor de `Rhat` será próximo a 1.]\nes inferior a 1.1 y el de `ESS`\n^[`ESS` (Efficient Sample Size) es una estimación del número de muestras independientes obtenidas en el muestreo $MCMC$.]\nsuperior a 400 en todos los parámetros, que son umbrales que no se deberían violar [ver @burkner2019]. En la\n@fig-trace se comprueba que las cadenas $MCMC$ de muestreo de la distribución a posteriori se mezclan correctamente y no se aprecia autocorrelación en ninguno de los parámetros. Por último, en la @fig-predictive se muestra una comparación entre los histogramas construidos con los datos de las respuestas a los test con los intervalos de credibilidad marginales de la función predictiva a posteriori del modelo. En la mayoría de los ítems el muestreo se ajusta bastante bien al histograma de respuestas; aunque en algunos ítems, como el `Q16` o el `Q17`, se aprecian diferencias relevantes.\n \n\n::: {.cell hash='4_cache/pdf/fig-trace_70a50eb387b515988deaaac8fe779ef4'}\n::: {.cell-output-display}\n![Cadenas MCMC del modelo Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Item).](4_files/figure-pdf/fig-trace-1.pdf){#fig-trace fig-scap='Cadenas MCMC del modelo seleccionado.'}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Comparación de los valores reales con los obtenidos a partir de la función predictiva a posteriori del modelo Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Item).](4_files/figure-pdf/fig-predictive-1.pdf){#fig-predictive fig-scap='Verificación usando la función predictiva a posteriori del modelo seleccionado.'}\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"tbl-washout\",\"tbl-washout\",\"tbl-washout\",\"tbl-distinct2\",\"tbl-distinct2\",\"tbl-distinct2\",\"tbl-noanswer\",\"tbl-noanswer\",\"tbl-noanswer\",\"tbl-diff\",\"tbl-diff\",\"tbl-diff\",\"tbl-resume\",\"tbl-resume\",\"tbl-resume\",\"tbl-no-response\",\"tbl-no-response\",\"tbl-no-response\",\"tbl-po.check\",\"tbl-po.check\",\"tbl-po.check\",\"tbl-contrast\",\"tbl-contrast\",\"tbl-contrast\",\"tbl-ordinal-com\",\"tbl-ordinal-com\",\"tbl-ordinal-com\",\"tbl-priors\",\"tbl-priors\",\"tbl-priors\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}