
## Regresión Ordinal

::: {.notes}
pag 38-50

Comentar que no es igual que la figura 4.6 de la página 39 de la memoria
:::

:::: {.columns}
::: {.column width="50%"}

```{r}
#| fig-cap: Comprobación de la proporcionalidad de *odds*.
#| fig-height: 10
po.check <- function(x, responses = 1:4) {
    df <- df_response
    if (x != "Overall") {
        df <- df %>% group_by(.data[[x]], Response)
    } else {
        df <- df %>% group_by(Response)
    }
    df <- df %>%
        count() %>%
        ungroup(Response) %>%
        mutate(cum.sum = cumsum(n), logit = qlogis(cum.sum / last(cum.sum))) %>%
        arrange(Response) %>%
        filter(Response %in% responses) %>%
        mutate(Predictor = x)
    if (x != "Overall") {
        df <- df %>% rename_with(~"Value", x)
    } else {
        df <- df %>% mutate(Value = "Overall")
    }
    return(df %>% mutate(Response = recode_factor(Response, "1" = "Y ≤ 1", "2" = "Y ≤ 2", "3" = "Y ≤ 3", "4" = "Y ≤ 4", "5" = "Y ≤ 5")))
}


bind_rows(po.check("Item"), po.check("Period"), po.check("Seq"), po.check("Treat"), po.check("Overall")) %>%
    mutate(Predictor = factor(Predictor, levels = c("Overall", "Treat", "Period", "Seq", "Item"))) %>%
    ggplot(aes(
        x = logit, y = Value,
        shape = Response, color = Response
    )) +
    geom_point(size = 3) +
    facet_grid(
        rows = vars(Predictor), scales = "free_y",
        space = "free", switch = "both"
    ) +
    theme(panel.spacing.y = unit(0.2, "lines"))
```

:::
::: {.column width="50%"}

```{r}
#| tbl-cap: Comprobación de la proporcionalidad de *odds* para Seq.
po.check("Seq", responses = 1:5) %>%
    dplyr::select(c("Response", "n", "cum.sum", "logit")) %>%
    gt() %>%
    fmt_number(columns = c("logit")) %>%
    tab_options(table.font.size = 30)
```
:::
:::
