<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.306">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="TFM UNED Máster en Ingeniería y Ciencia de Datos">

<title>Utilización de técnicas multivariantes para el estudio del aprendizaje de la mejora de la accesibilidad en el subtitulado de vídeos - 8&nbsp; Modelado estadístico.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./50-Resultados.html" rel="next">
<link href="./42-Analisis.html" rel="prev">
<link href="./images/logo.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./43-Modelado.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Modelado estadístico.</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Utilización de técnicas multivariantes para el estudio del aprendizaje de la mejora de la accesibilidad en el subtitulado de vídeos</a> 
        <div class="sidebar-tools-main">
    <a href="./Utilización-de-técnicas-multivariantes-para-el-estudio-del-aprendizaje-de-la-mejora-de-la-accesibilidad-en-el-subtitulado-de-vídeos.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Utilities for R.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-Arte.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estado del arte</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-Metodos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Materiales y métodos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31-Preprocesamiento.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Métodos.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./32-Modelo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelo.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./40-EDA1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Exploración inicial.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./42-Analisis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Análisis estadístico.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./43-Modelado.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Modelado estadístico.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./50-Resultados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Resultados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./60-Conclusiones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Conclusiones y trabajo futuro</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-Referencias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Apéndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./75-Preprocesado.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Preprocesado de los ficheros suministrados.</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./76-Setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Creación de los <code>dataframes df_all</code> y <code>df_clean</code>.</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./77-Contrasts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Efecto secuencia e interacción tratamiento vs.&nbsp;periodo.</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./78-Bayesiano.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Modelado Bayesiano.</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#árboles-de-inferencia-condicional." id="toc-árboles-de-inferencia-condicional." class="nav-link active" data-scroll-target="#árboles-de-inferencia-condicional."><span class="header-section-number">8.1</span> Árboles de inferencia condicional.</a></li>
  <li><a href="#regresión-ordinal." id="toc-regresión-ordinal." class="nav-link" data-scroll-target="#regresión-ordinal."><span class="header-section-number">8.2</span> Regresión ordinal.</a>
  <ul class="collapse">
  <li><a href="#variantes-de-la-regresión-ordinal." id="toc-variantes-de-la-regresión-ordinal." class="nav-link" data-scroll-target="#variantes-de-la-regresión-ordinal."><span class="header-section-number">8.2.1</span> Variantes de la Regresión Ordinal.</a></li>
  <li><a href="#ajuste-del-modelo-ordinal-response-treat." id="toc-ajuste-del-modelo-ordinal-response-treat." class="nav-link" data-scroll-target="#ajuste-del-modelo-ordinal-response-treat."><span class="header-section-number">8.2.2</span> Ajuste del modelo ordinal <code>Response ~ Treat</code>.</a></li>
  <li><a href="#ajuste-del-modelo-ordinal-response-treat-period." id="toc-ajuste-del-modelo-ordinal-response-treat-period." class="nav-link" data-scroll-target="#ajuste-del-modelo-ordinal-response-treat-period."><span class="header-section-number">8.2.3</span> Ajuste del modelo ordinal <code>Response ~ Treat + Period</code>.</a></li>
  <li><a href="#ajuste-del-modelo-ordinal-response-treat-period.-1" id="toc-ajuste-del-modelo-ordinal-response-treat-period.-1" class="nav-link" data-scroll-target="#ajuste-del-modelo-ordinal-response-treat-period.-1"><span class="header-section-number">8.2.4</span> Ajuste del modelo ordinal <code>Response ~ Treat * Period.</code></a></li>
  <li><a href="#elección-del-modelo-ordinal-mediante-el-test-de-razón-de-verosimilitud." id="toc-elección-del-modelo-ordinal-mediante-el-test-de-razón-de-verosimilitud." class="nav-link" data-scroll-target="#elección-del-modelo-ordinal-mediante-el-test-de-razón-de-verosimilitud."><span class="header-section-number">8.2.5</span> Elección del modelo ordinal mediante el test de razón de verosimilitud.</a></li>
  <li><a href="#comprobación-de-las-hipótesis-del-modelo." id="toc-comprobación-de-las-hipótesis-del-modelo." class="nav-link" data-scroll-target="#comprobación-de-las-hipótesis-del-modelo."><span class="header-section-number">8.2.6</span> Comprobación de las hipótesis del modelo.</a></li>
  <li><a href="#introducción-a-los-modelos-multinivel." id="toc-introducción-a-los-modelos-multinivel." class="nav-link" data-scroll-target="#introducción-a-los-modelos-multinivel."><span class="header-section-number">8.2.7</span> Introducción a los modelos multinivel.</a></li>
  <li><a href="#ajuste-del-modelo-multinivel-ordinal." id="toc-ajuste-del-modelo-multinivel-ordinal." class="nav-link" data-scroll-target="#ajuste-del-modelo-multinivel-ordinal."><span class="header-section-number">8.2.8</span> Ajuste del modelo multinivel ordinal.</a></li>
  </ul></li>
  <li><a href="#modelado-bayesiano." id="toc-modelado-bayesiano." class="nav-link" data-scroll-target="#modelado-bayesiano."><span class="header-section-number">8.3</span> Modelado Bayesiano.</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Modelado estadístico.</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Vamos a construir diversos modelos para analizar la asociación de la variable respuesta sobre los dos niveles de subtitulado y la interacción con el periodo y la secuencia de tratamientos.</p>
<section id="árboles-de-inferencia-condicional." class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="árboles-de-inferencia-condicional."><span class="header-section-number">8.1</span> Árboles de inferencia condicional.</h2>
<p>Los arboles de inferencia condicional (CIT) son un tipo de árbol de decisión en el que la selección de variables y de los puntos de división no se basan en medidas de homogeneidad como el índice de Gini, sino en un contrastes de hipótesis no paramétricos. El algoritmo que se utiliza es el siguiente, ver <span class="citation" data-cites="Levshina2020">Levshina (<a href="99-Referencias.html#ref-Levshina2020" role="doc-biblioref">2020</a>)</span>:</p>
<p>El algoritmo consiste en contrastar la hipótesis nula de si la variable de respuesta <span class="math inline">\(Y\)</span> es independiente de alguna variable explicativa <span class="math inline">\(Y \mid X\)</span>. Para probar la hipótesis, se utiliza un algoritmo de permutación de la variable respuesta y se mide la asociación con la variable explicativa antes y después de la permutación. Si la asociación no varía significativamente, podemos asumir que las variables de respuesta y explicativa son independientes. De esta forma se selecciona la variable explicativa que más influye en la respuesta y que se utilizará en el particionado. Para elegir el valor de la variable explicativa que dividirá el conjunto de datos, se procede de forma análoga midiendo el cambio en la diferencia de asociación. De acuerdo con <span class="citation" data-cites="frienly2015-2">Friendly (<a href="99-Referencias.html#ref-frienly2015-2" role="doc-biblioref">2015</a>)</span>, los CIT resuelven los problemas de sobreajuste de los árboles de decisión tradicionales.</p>
<p>Para realizar el particionado basado en CIT, vamos a usar la función <code>ctree</code> del paquete <code>party</code> de R. Presentamos aquí únicamente el modelo final elegido que incluye como variables explicativas <code>Treat</code>, <code>Period</code>, <code>Seq</code> y <code>Cluster</code> <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<p>En la <a href="#fig-ctree">Figura&nbsp;<span>8.1</span></a> podemos ver que el nivel de subtitulado es el efecto principal, seguido del grupo de preguntas y finalmente la secuencia. En este modelo el periodo no aparece por no estar asociado con la respuesta. Estos resultados son contradictorios con los que obtuvimos en el análisis con el OR (ver <a href="42-Analisis.html#sec-or"><span>Sección&nbsp;7.2.3</span></a>) en el que el factor secuencia no era significativo pero sí lo era el factor periodo. Por otro lado, vemos que la asociación más fuerte es el nivel de respuesta 5 para subtitulado <span class="math inline">\(A\)</span>, grupos de preguntas 1 y 2 y secuencia <span class="math inline">\(AB\)</span> y de las respuestas 4 y 5 cuando la secuencia es <span class="math inline">\(BA\)</span>. El tratamiento <span class="math inline">\(B\)</span> está fuertemente asociado con el nivel de respuesta 1 para el grupo de preguntas 1. Por último, con este modelo no hay ninguna combinación de factores que prediga un nivel de respuesta 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>tree<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">ctree</span>(Response <span class="sc">~</span> Treat <span class="sc">+</span> Cluster <span class="sc">+</span> Period <span class="sc">+</span> Seq, <span class="at">data =</span> df_clean)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ctree" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="43-Modelado_files/figure-html/fig-ctree-1.png" class="img-fluid figure-img" width="960"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8.1: Modelo con árboles de inferencia condicional (Response ~ Treat + Cluster + Period + Seq).</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Aunque no es el objetivo del trabajo, podemos usar este modelo para hacer predicciones. La matriz de contingencia resultante es la siguiente:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         Prediction
Reference   1   2   3   4   5
        1   0 111  19  36   1
        2   0 178  53 170  13
        3   0  67  94 181  41
        4   0  94  76 629 158
        5   0  70  44 560 385</code></pre>
</div>
</div>
<p>Como habíamos anticipado, nunca se predice el nivel de respuesta 1. Las categorías que más probablemente predice nuestro modelo son la 4 y la 5 pero aún así hay mucha confusión entre ellas. La exactitud de predicción es 43%.</p>
<p>Un modelo alternativo sería usar las mismas variables explicativas pero cambiado <code>Response</code> por <code>Level</code> como variable de respuesta. Esta variable solo tiene tres niveles: positivo, negativo y neutro. De esta forma no se producen confusiones entre los niveles 1 y 2 por un lado y 4 y 5 por otro:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>tree<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">ctree</span>(Level <span class="sc">~</span> Treat <span class="sc">+</span> Cluster <span class="sc">+</span> Period <span class="sc">+</span> Seq, <span class="at">data =</span> df_clean)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ctree2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="43-Modelado_files/figure-html/fig-ctree2-1.png" class="img-fluid figure-img" width="960"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8.2: Modelo con árboles de inferencia condicional (Level ~ Treat + Cluster + Period + Seq).</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>El árbol obtenido con variable respuesta <code>Level</code> (ver <a href="#fig-ctree2">Figura&nbsp;<span>8.2</span></a>) es muy similar al otro (ver <a href="#fig-ctree">Figura&nbsp;<span>8.1</span></a>) con la principal diferencia de que ahora la secuencia ha desaparecido como factor relevante. Por otro lado, el modelo siempre predice una respuesta positiva excepto para el subtitulado <span class="math inline">\(B\)</span> y grupo de preguntas 1, que es negativa (el nivel neutro nunca se predice). La exactitud del modelo ha subido a 72%. En cualquier caso no es una gran mejora ya que un modelo que predijera siempre la categoría mayoritaria (positiva), habría obtenido una exactitud de 68%. Se han hecho simulaciones consistentes en incluir como factor las preguntas o usar como modelo un árbol de decisión convencional con resultados similares.</p>
</section>
<section id="regresión-ordinal." class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="regresión-ordinal."><span class="header-section-number">8.2</span> Regresión ordinal.</h2>
<p>El test de Likert es una escala ordinal. Los test estadísticos ANOVA o MANOVA presuponen que la variable de respuesta es cuantitativa y con distribución normal. Tratar las respuestas a un test de Likert como si fueran cuantitativas no es correcto por las siguientes razones:</p>
<ul>
<li><p>Los niveles de respuesta no son necesariamente equidistantes: la distancia entre un par de opciones de respuesta puede no ser la misma para todos los pares de opciones de respuesta. Por ejemplo, la diferencia entre “Muy en desacuerdo” y “En desacuerdo” y la diferencia entre “De acuerdo” y “Muy de acuerdo” es de un nivel, pero psicológicamente puede ser percibida de forma diferente por cada sujeto.</p></li>
<li><p>La distribución de las respuestas ordinales puede ser no normal. En particular esto sucederá si hay muchas respuestas en los extremos del cuestionario.</p></li>
<li><p>Las varianzas de las variables no observadas que subyacen a las variables ordinales observadas pueden diferir entre grupos, tratamientos, periodos, etc.</p></li>
</ul>
<p>En <span class="citation" data-cites="kruschke2018">Liddell y Kruschke (<a href="99-Referencias.html#ref-kruschke2018" role="doc-biblioref">2018</a>)</span> se han analizado los problemas potenciales de tratar datos ordinales como si fueran cuantitativos constatando que se pueden presentar las siguientes situaciones:</p>
<ul>
<li>Se pueden encontrar diferencias significativas entre grupos cuando no las hay: error tipo I.</li>
<li>Se pueden obviar diferencias cuando en realidad sí existen: error tipo II.</li>
<li>Incluso se pueden invertir los efectos de un tratamiento.</li>
<li>También puede malinterpretarse la interacción entre factores.</li>
</ul>
<p>La Regresión Logística Multinomial es una extensión de la Regresión Logística cuando la variable de respuesta es nominal. La Regresión Ordinal tiene en consideración que los valores nominales de la variable de respuesta están ordenados y por eso será el modelo que utilizaremos.</p>
<section id="variantes-de-la-regresión-ordinal." class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="variantes-de-la-regresión-ordinal."><span class="header-section-number">8.2.1</span> Variantes de la Regresión Ordinal.</h3>
<p>Los modelos lineales generalizados (<span class="math inline">\(GLM\)</span>) son modelos en los que la variable respuesta no es normal. Para especificar un <span class="math inline">\(GLM\)</span> son necesarios tres componentes <span class="citation" data-cites="oconnell2006">(ver <a href="99-Referencias.html#ref-oconnell2006" role="doc-biblioref">O’Connell 2006</a>)</span>:</p>
<ul>
<li>Un componente aleatorio: será una distribución de probabilidad de la familia exponencial que se asume que sigue la variable respuesta (en la regresión logística será la distribución Binomial o la distribución de Bernoulli).</li>
<li>Un componente lineal de predictores.</li>
<li>Una función de enlace que realiza transformación de los valores del componente lineal a los que puede tomar la variable respuesta. Por ejemplo en la función logística será la función <span class="math inline">\(logit^{-1}(x)\)</span>. Esta función permite pasar de un rango de valores <span class="math inline">\((-\infty, +\infty)\)</span> a un rango <span class="math inline">\((0, 1)\)</span>.</li>
</ul>
<p>La Regresión Ordinal es una extensión de la Regresión Logística y, por lo tanto de <span class="math inline">\(GLM\)</span>. Según <span class="citation" data-cites="burkner2019">Bürkner y Vuorre (<a href="99-Referencias.html#ref-burkner2019" role="doc-biblioref">2019</a>)</span> hay tres clases de Regresión Ordinal:</p>
<ul>
<li>Regresión ordinal acumulativa.</li>
<li>Regresión ordinal secuencial.</li>
<li>Regresión ordinal adyacente.</li>
</ul>
<p>Nos centraremos en la primera ya que es la más habitual y adecuada para nuestro caso <span class="citation" data-cites="burkner2019">(ver <a href="99-Referencias.html#ref-burkner2019" role="doc-biblioref">Bürkner y Vuorre 2019, 23-24</a>)</span>. El modelo acumulativo, CM, presupone que la variable ordinal observada, <span class="math inline">\(Y\)</span>, proviene de la categorización de una variable latente (no observada) continua, <span class="math inline">\(\tilde{Y}\)</span>. Hay <span class="math inline">\(K\)</span> umbrales <span class="math inline">\(\tau_k\)</span> que particionan <span class="math inline">\(\tilde{Y}\)</span> en <span class="math inline">\(K + 1\)</span> categorías ordenadas observables (ver <a href="#fig-cumulative">Figura&nbsp;<span>8.3</span></a>). Si asumimos que <span class="math inline">\(\tilde{Y}\)</span> tiene una cierta distribución (por ejemplo, normal) con distribución acumulada <span class="math inline">\(F\)</span>, se puede calcular la probabilidad de que <span class="math inline">\(Y\)</span> sea la categoría <span class="math inline">\(k\)</span> de esta forma:</p>
<p><span class="math display">\[Pr(Y = k) = F(\tau_k) - F(\tau_{k-1})\]</span></p>
<div class="cell" data-freeze="true">
<div class="cell-output-display">
<div id="fig-cumulative" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="43-Modelado_files/figure-html/fig-cumulative-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8.3: Función latente en una regresión ordinal acumulativa.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Por ejemplo en la <a href="#fig-cumulative">Figura&nbsp;<span>8.3</span></a>,</p>
<p><span class="math display">\[Pr(Y = 2) = F(\tau_2) - F(\tau_{1})\]</span></p>
<p>Si suponemos que <span class="math inline">\(\tilde{Y}\)</span> tiene una relación lineal los predictores:</p>
<p><span class="math display">\[\tilde{Y} = \eta + \epsilon = \beta_1 x_1 + \beta_2 x_2 + ... + \beta_p x_p + \epsilon\]</span>,</p>
<p>y que los errores son <span class="math inline">\(N(0,\sigma^2)\)</span>. Entonces la función de probabilidad acumulada de los errores tendrá la misma forma que la de <span class="math inline">\(\tilde{Y}\)</span>:</p>
<p><span class="math display">\[\mathrm{Pr}(\epsilon \leq z) = F(z)\]</span></p>
<p>Y podremos calcular la distribución de probabilidad acumulada de <span class="math inline">\(Y\)</span>:</p>
<p><span class="math display">\[\mathrm{Pr}(Y \leq k \mid \eta) = \mathrm{Pr}(\tilde{Y} \leq \tau_k \mid \eta) = \mathrm{Pr}(\eta + \epsilon \leq \tau_k) = \mathrm{Pr}(\epsilon \leq \tau_k - \eta) = F(\tau_k - \eta)\]</span></p>
<p>Por lo que asumiendo la normalidad de los errores:</p>
<p><span class="math display">\[\mathrm{Pr}(Y = k) = \Phi(\tau_k - \eta) - \Phi(\tau_{k - 1} - \eta)\]</span></p>
<p>Donde hay que estimar los umbrales y los coeficientes de regresión. La función anterior es la conocida como la función de enlace <code>probit</code>. Otra función de enlace popular es la función <code>logit</code>. Es la que usaremos en este trabajo por ser más fácil su interpretación <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Con esta función de enlace la interpretación de los coeficientes es parecida a la de los coeficientes de la regresión logística. Se parte del supuesto de que el <span class="math inline">\(logit\)</span> de la función de probabilidad es lineal:</p>
<p><span class="math display">\[logit [P(Y \le k)] = \tau_{k} - \eta = \tau_{k} - (\beta_1 x_1 + \beta_2 x_2 + ... + \beta_p x_p)\]</span></p>
<p>En ese caso, se puede demostrar fácilmente que, por ejemplo:</p>
<p><span class="math display">\[\frac{\frac{\mathrm{Pr}(Y \leq k \mid \eta)}{\mathrm{Pr}(Y &gt; k \mid \eta)}}{\frac{\mathrm{Pr}(Y \leq k+1 \mid \eta)}{\mathrm{Pr}(Y &gt; k+1 \mid \eta)}} = \exp(\tau_{k} - \tau_{k+1})\]</span></p>
<p>Y que <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>:</p>
<p><span class="math display">\[\frac{\frac{\mathrm{Pr}(Y \leq k \mid x_i = 1)}{\mathrm{Pr}(Y &gt; k \mid x_i = 1)}}{\frac{\mathrm{Pr}(Y \leq k \mid x_i=0)}{\mathrm{Pr}(Y &gt; k \mid x_i = 0)}} = \exp(-\beta_{i})\]</span></p>
<p>o, equivalentemente:</p>
<p><span class="math display">\[\frac{\frac{\mathrm{Pr}(Y &gt; k \mid x_i = x + 1)}{\mathrm{Pr}(Y \leq k \mid x_i = x + 1)}}{\frac{\mathrm{Pr}(Y &gt; k \mid x_i = x)}{\mathrm{Pr}(Y \leq k \mid x_i = x)}} = \exp(\beta_{i})\]</span></p>
<p>Es decir, que <span class="math inline">\(\exp(\beta_{i})\)</span> es el <span class="math inline">\(OR\)</span> (cambio en <span class="math inline">\(odds\)</span>) de que la variable respuesta esté por encima de una determinada categoría versus estar por debajo de ella para una unidad de incremento del predictor <span class="math inline">\(x_i\)</span>. Este modelo se denomina proporcional ya que cada predictor se asume que tiene los mismos efectos sobre todas las categorías de la variable de respuesta ordinal <span class="citation" data-cites="Liu2202">(ver <a href="99-Referencias.html#ref-Liu2202" role="doc-biblioref">Liu 2022</a>)</span>. Un valor del coeficiente <span class="math inline">\(\beta_i\)</span> positivo indica que la relación entre el predictor <span class="math inline">\(x_i\)</span> y la función de <span class="math inline">\(logit\)</span> es positiva y, por lo tanto, se incrementa la posibilidad de un mayor valor de la variable respuesta. Como veremos, esta suposición se puede relajar y permitir que los coeficientes de todos o de algunos de los predictores sean diferentes para cada pareja consecutiva de valores de respuesta. Tendríamos entonces más parámetros a estimar con una interpretación más compleja.</p>
</section>
<section id="ajuste-del-modelo-ordinal-response-treat." class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="ajuste-del-modelo-ordinal-response-treat."><span class="header-section-number">8.2.2</span> Ajuste del modelo ordinal <code>Response ~ Treat</code>.</h3>
<p>Existen varios paquetes en R que permiten ajustar una regresión ordinal logística. El más popular es el paquete <code>Ordinal</code> <span class="citation" data-cites="ordinalR">(<a href="99-Referencias.html#ref-ordinalR" role="doc-biblioref">R. H. B. Christensen 2022</a>)</span>. El paquete <code>VGAM</code> <span class="citation" data-cites="VGAMR">(<a href="99-Referencias.html#ref-VGAMR" role="doc-biblioref">Yee 2023</a>)</span> es más flexible y potente. Otra posibilidad es usar la función <code>polr</code> del paquete <code>MASS</code> <span class="citation" data-cites="MASSR">(<a href="99-Referencias.html#ref-MASSR" role="doc-biblioref">Venables y Ripley 2002</a>)</span>. Finalmente la función <code>orm</code> del paquete <code>rms</code> también permite hacerlo <span class="citation" data-cites="harrell2015">(ver <a href="99-Referencias.html#ref-harrell2015" role="doc-biblioref">Harrell 2015</a>)</span>. En este trabajo usaremos el paquete <code>Ordinal</code> por permitir también incluir efectos aleatorios que utilizaremos en un apartado posterior. Comenzamos con un modelo simple que tiene como único predictor el nivel de subtitulado por ser la variable objetivo de nuestro modelo:</p>
<p><span class="math display">\[
\text{logit}(P(Response_i \leq k)) = \tau_k - \beta_1 \text{Treat}_i,
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>clm_treat <span class="ot">&lt;-</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">clm</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>        Response <span class="sc">~</span> Treat,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> df_clean, <span class="at">link =</span> <span class="st">"logit"</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clm_treat)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>formula: Response ~ Treat
data:    df_clean

 link  threshold nobs logLik   AIC     niter max.grad cond.H 
 logit flexible  2980 -3966.11 7942.21 5(0)  1.64e-10 3.1e+01

Coefficients:
       Estimate Std. Error z value Pr(&gt;|z|)    
TreatB  -1.7206     0.0731  -23.54   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
    Estimate Std. Error z value
1|2 -3.97230    0.09678 -41.045
2|3 -2.45446    0.06812 -36.029
3|4 -1.66453    0.05936 -28.042
4|5 -0.10547    0.04946  -2.132</code></pre>
</div>
</div>
<p>El método <code>summary()</code> muestra la información resumen. Para su interpretación vamos a seguir <span class="citation" data-cites="christensen2018CumulativeLM">Rune Haubo Bojesen Christensen (<a href="99-Referencias.html#ref-christensen2018CumulativeLM" role="doc-biblioref">2018</a>)</span>. El número de condición Hessiano es inferior a <span class="math inline">\(10^4\)</span> lo que es indicativo de que no hay problemas de optimización <a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. La sección de coeficientes es la más importante. Se muestra la estimación de parámetros, el error estándar y la significación estadística de acuerdo al test de Wald <a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>. Comprobamos que el valor es claramente significativo. Es decir, que los estudiantes han valorado de forma diferente la calidad del subtitulado en ambos vídeos. El estimador de maxima verosimilitud del coeficiente <code>TreatB</code> es -1.72. Siguiendo la deducción de <span class="citation" data-cites="bruin2011">Bruin (<a href="99-Referencias.html#ref-bruin2011" role="doc-biblioref">2011</a>)</span> podemos, por ejemplo, hacer la siguiente interpretación del significado de este coeficiente referido a dos niveles consecutivos de respuesta:</p>
<p><span class="math display">\[
\begin{aligned}
logit [P(Y \le 1)] &amp; = &amp; -3.97 - (-1.72 x_1) \\
logit [P(Y \le 2)] &amp; = &amp; -2.45 - (-1.72 x_1)
\end{aligned}
\]</span></p>
<p>Por lo tanto los <span class="math inline">\(odds\)</span> serían:</p>
<p><span class="math display">\[
\begin{aligned}
\frac{P(Y \le 1 \mid x_1 = B)}{P(Y &gt; 1 \mid x_1 = B)} &amp; = &amp; exp(-3.97)/exp(-1.72) \\
\frac{P(Y \le 1 \mid x_1 = A)}{P(Y &gt; 1 \mid x_1 = A)} &amp; = &amp; exp(-3.97) \\
\frac{P(Y \le 2 \mid x_1 = B)}{P(Y &gt; 2 \mid x_1 = B)} &amp; = &amp; exp(-2.45)/exp(-1.72) \\
\frac{P(Y \le 2 \mid x_1 = A)}{P(Y &gt; 2 \mid x_1 = A)} &amp; = &amp; exp(-2.45)
\end{aligned}
\]</span></p>
<p>Y los <span class="math inline">\(OR\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
\frac{P(Y \le 1 | x_1=B)}{P(Y &gt; 1 | x_1=B)} / \frac{P(Y \le 1 | x_1=A)}{P(Y &gt; 1 | x_1=A)} &amp; = &amp; 1/exp(-1.72) &amp; = &amp; 5.59 \\
\frac{P(Y \le 2 | x_1=B)}{P(Y &gt; 2 | x_1=B)} / \frac{P(Y \le 2 | x_1=A)}{P(Y &gt; 2 | x_1=A)} &amp; = &amp; 1/exp(-1.72) &amp; = &amp; 5.59 \\
\end{aligned}
\]</span></p>
<p>Se comprueba que el <span class="math inline">\(OR\)</span> es equivalente en todos los niveles de respuesta al cuestionario. Esta es una de las suposiciones de la regresión ordinal acumulativa. El <span class="math inline">\(odds\)</span> de respuesta al cuestionario entre los niveles inferiores y superiores a uno dado, <span class="math inline">\(k\)</span>, es 5.59 veces en el subtitulado <span class="math inline">\(B\)</span> que en el <span class="math inline">\(A\)</span>. Esto indica que el subtitulado <span class="math inline">\(B\)</span> es percibido por los estudiantes como de peor calidad que el subtitulado <span class="math inline">\(A\)</span>. Concretamente, el coeficiente <span class="math inline">\(\beta\)</span> para <code>Treat</code> es el <code>log odds</code> de observar una mejor respuesta en una pregunta del test es 5.59 veces superior en el nivel de subtitulado <span class="math inline">\(A\)</span> que en el <span class="math inline">\(B\)</span>. Aunque no suele ser de interés la interpretación de los coeficientes de los umbrales (<code>Threshold coefficients</code>), se pueden utilizar para estimar las probabilidades de respuesta. Por ejemplo, para el nivel de subtitulado <span class="math inline">\(B\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
logit [P(Y \le 1)] &amp; = &amp; -3.97 - (-1.72) &amp; = &amp; -2.25 \\
odds (P(Y \le 1)) &amp; = &amp; exp(logit [P(Y \le 1)]) &amp; = &amp; 0.11 \\
P(Y \le 1) &amp; = &amp; \frac{exp(-2.25)}{1 + exp(-2.25)} &amp; = &amp; 0.10 \\
P(Y \le 2) &amp; = &amp; \frac{exp(-0.73)}{1 + exp(-0.73)} &amp; = &amp; 0.32 \\
P(Y = 2) &amp; = &amp; P(Y \le 2) - P(Y \le 1) &amp; = &amp;  0.23
\end{aligned}
\]</span></p>
<p>Para el subtitulado <span class="math inline">\(A\)</span> no se tiene en cuenta el coeficiente <span class="math inline">\(TreatB\)</span> ya que el valor <span class="math inline">\(x_1\)</span> es cero:</p>
<p><span class="math display">\[
\begin{aligned}
logit [P(Y \le 1)] &amp; = &amp; &amp; &amp; -3.97\\
odds (P(Y \le 1)) &amp; = &amp; exp(logit [P(Y \le 1)]) &amp; = &amp; 0.02 \\
P(Y \le 1) &amp; = &amp; \frac{exp(-3.97)}{1 + exp(-3.97)} &amp; = &amp; 0.02
\end{aligned}
\]</span></p>
<p>En <a href="#tbl-probs-clm-treat">Tabla&nbsp;<span>8.1</span></a> se muestran las probabilidades para ambos niveles de subtitulado y todos los posibles valores de respuesta.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-probs-clm-treat" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabla&nbsp;8.1: Probabilidades de respuesta para el modelo ordinal Response ~ Treat</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">3</th>
<th style="text-align: right;">4</th>
<th style="text-align: right;">5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">0.018</td>
<td style="text-align: right;">0.061</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.315</td>
<td style="text-align: right;">0.526</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">0.095</td>
<td style="text-align: right;">0.229</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">0.320</td>
<td style="text-align: right;">0.166</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="ajuste-del-modelo-ordinal-response-treat-period." class="level3" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="ajuste-del-modelo-ordinal-response-treat-period."><span class="header-section-number">8.2.3</span> Ajuste del modelo ordinal <code>Response ~ Treat + Period</code>.</h3>
<p>Para saber si existe un efecto periodo, añadimos como predictor la variable <code>Period</code>.</p>
<p><span class="math display">\[
\text{logit}(P(Response_i \leq k)) = \tau_k - \beta_1 \text{Treat}_i - \beta_2 \text{Period}_i
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>clm_treat_period <span class="ot">&lt;-</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">clm</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>        Response <span class="sc">~</span> Treat <span class="sc">+</span> Period,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> df_clean, <span class="at">link =</span> <span class="st">"logit"</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clm_treat_period)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>formula: Response ~ Treat + Period
data:    df_clean

 link  threshold nobs logLik   AIC     niter max.grad cond.H 
 logit flexible  2980 -3957.88 7927.76 5(0)  1.94e-10 4.1e+01

Coefficients:
        Estimate Std. Error z value Pr(&gt;|z|)    
TreatB  -1.74090    0.07339  -23.72  &lt; 2e-16 ***
Period2 -0.27560    0.06805   -4.05 5.12e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
    Estimate Std. Error z value
1|2 -4.13085    0.10507 -39.314
2|3 -2.60905    0.07872 -33.143
3|4 -1.81652    0.07073 -25.681
4|5 -0.25187    0.06153  -4.093</code></pre>
</div>
</div>
<p>Vemos que ambos coeficientes son significativos y con signo negativo. Un signo negativo en el efecto periodo está asociado con que la valoración del subtitulado empeora en el segundo periodo independientemente de si se trata del subtitulado correcto o incorrecto. Aplicando el mismo razonamiento del apartado anterior, el <span class="math inline">\(OR\)</span> del efecto periodo es <span class="math inline">\(1/exp(-0.28) = 1.32\)</span>. Lo que quiere decir que una vez controlado el efecto principal del tratamiento, el subtitulado en el segundo periodo es valorado como de inferior calidad que en el primero. Esto estaría indicando que los estudiantes son más exigentes con el subtitulado en la segunda actividad independientemente de su calidad real.</p>
</section>
<section id="ajuste-del-modelo-ordinal-response-treat-period.-1" class="level3" data-number="8.2.4">
<h3 data-number="8.2.4" class="anchored" data-anchor-id="ajuste-del-modelo-ordinal-response-treat-period.-1"><span class="header-section-number">8.2.4</span> Ajuste del modelo ordinal <code>Response ~ Treat * Period.</code></h3>
<p>Añadimos al modelo la interacción entre subtitulado y periodo. Esta interacción corresponde al efecto secuencia. Se puede demostrar que los modelos <code>Response ~ Treat*Period</code> y <code>Response ~ Treat + Period + Seq</code> son equivalentes si se cambia el contraste por defecto utilizado en R, que es <code>treatment</code>, a <code>sum</code> <a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> <span class="fu">rep</span>(<span class="st">"contr.sum"</span>, <span class="dv">2</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>clm_treat_period_seq.sum <span class="ot">&lt;-</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">clm</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>        Response <span class="sc">~</span> Treat <span class="sc">+</span> Period <span class="sc">+</span> Seq,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> df_clean, <span class="at">link =</span> <span class="st">"logit"</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(clm_treat_period_seq.sum)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1|2        2|3        3|4        4|5     Treat1    Period1       Seq1 
-3.1266457 -1.6083838 -0.8184857  0.7499332  0.8739547  0.1396182  0.1062749 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> <span class="fu">rep</span>(<span class="st">"contr.sum"</span>, <span class="dv">2</span>))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>clm_treat.period.sum <span class="ot">&lt;-</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">clm</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>        Response <span class="sc">~</span> Treat <span class="sc">*</span> Period,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> df_clean, <span class="at">link =</span> <span class="st">"logit"</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(clm_treat.period.sum)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           1|2            2|3            3|4            4|5         Treat1 
    -3.1266457     -1.6083838     -0.8184857      0.7499332      0.8739547 
       Period1 Treat1:Period1 
     0.1396182      0.1062749 </code></pre>
</div>
</div>
<p>Vemos que los coeficientes <code>Seq1</code> y <code>Treat1:Period1</code> son iguales y, por lo tanto, queda demostrado que la secuencia es la interacción entre periodo y tratamiento. Sin embargo los coeficientes son diferentes si el contraste es <code>treatment</code> <a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> <span class="fu">rep</span>(<span class="st">"contr.treatment"</span>, <span class="dv">2</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>clm_treat_period_seq <span class="ot">&lt;-</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">clm</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>        Response <span class="sc">~</span> Treat <span class="sc">+</span> Period <span class="sc">+</span> Seq,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> df_clean, <span class="at">link =</span> <span class="st">"logit"</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(clm_treat_period_seq)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1|2        2|3        3|4        4|5     TreatB    Period2      SeqBA 
-4.2464935 -2.7282315 -1.9383335 -0.3699146 -1.7479094 -0.2792363 -0.2125498 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> <span class="fu">rep</span>(<span class="st">"contr.treatment"</span>, <span class="dv">2</span>))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>clm_treat.period <span class="ot">&lt;-</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">clm</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>        Response <span class="sc">~</span> Treat <span class="sc">*</span> Period,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> df_clean, <span class="at">link =</span> <span class="st">"logit"</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(clm_treat.period)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           1|2            2|3            3|4            4|5         TreatB 
    -4.2464935     -2.7282315     -1.9383335     -0.3699146     -1.9604592 
       Period2 TreatB:Period2 
    -0.4917861      0.4250996 </code></pre>
</div>
</div>
<p>En el <a href="77-Contrasts.html"><span>Apéndice&nbsp;C</span></a> se explica como se pueden obtener los coeficientes de un modelo a partir de los coeficientes de otro modelo. Es decir, que se pueden obtener los coeficientes del modelo <code>clm_treat.period</code> a partir de los coeficientes del modelo <code>clm_treat.period.sum</code>. Por ejemplo, el coeficiente <span class="math inline">\(TreatB\)</span> del modelo <code>clm_treat.period</code> se calcula:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>(<span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> (<span class="fu">coef</span>(clm_treat.period.sum)[<span class="st">"Treat1"</span>] <span class="sc">+</span> <span class="fu">coef</span>(clm_treat.period.sum)[<span class="st">"Treat1:Period1"</span>]))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Treat1 
-1.960459 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(clm_treat.period)[<span class="st">"TreatB"</span>]</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   TreatB 
-1.960459 </code></pre>
</div>
</div>
<p>Sin embargo la interpretación de los coeficientes del segundo modelo, <code>clm_treat.period</code>, es más sencilla ya que es la que estamos habituados a utilizar en R. Por ello en este análisis se utilizará el modelo <code>clm_treat.period</code>. El resumen del ajuste es:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clm_treat.period)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>formula: Response ~ Treat * Period
data:    df_clean

 link  threshold nobs logLik   AIC     niter max.grad cond.H 
 logit flexible  2980 -3953.01 7920.03 5(0)  2.14e-10 8.1e+01

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
TreatB         -1.96046    0.10229 -19.166  &lt; 2e-16 ***
Period2        -0.49179    0.09744  -5.047 4.49e-07 ***
TreatB:Period2  0.42510    0.13638   3.117  0.00183 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
    Estimate Std. Error z value
1|2 -4.24649    0.11182 -37.977
2|3 -2.72823    0.08821 -30.928
3|4 -1.93833    0.08167 -23.732
4|5 -0.36991    0.07308  -5.062</code></pre>
</div>
</div>
<p>Vemos que los tres coeficientes son significativos. El principal efecto es el nivel de subtitulado obteniendo mejores puntuaciones el nivel <span class="math inline">\(A\)</span>; el efecto periodo es negativo por lo que el primer periodo obtiene mejores puntuaciones; por último, el efecto secuencia es positivo pero de menor valor absoluto que el efecto periodo. Esto quiere decir que el subtitulado de nivel <span class="math inline">\(B\)</span> en el periodo 2 (secuencia <span class="math inline">\(AB\)</span>), tiene un efecto periodo inferior que el subtitulado <span class="math inline">\(A\)</span> en el mismo periodo. Matemáticamente:</p>
<p><span class="math display">\[
\begin{aligned}
logit [P(Y \le 1 \mid Treat = A, Period = 1)] &amp; = &amp; -4.25 \\
logit [P(Y \le 1 \mid Treat = B, Period = 1)] &amp; = &amp; -4.25 - (-1.96) \\
logit [P(Y \le 1 \mid Treat = A, Period = 2)] &amp; = &amp; -4.25 - (-0.49) \\
logit [P(Y \le 1 \mid Treat = B, Period = 2)] &amp; = &amp; -4.25 -(-1.96 -0.49 + 0.43)
\end{aligned}
\]</span></p>
<p>En definitiva, en el nivel de subtitulado <span class="math inline">\(B\)</span> apenas encontramos diferencias entre periodos, sin embargo, en el nivel de subtitulado <span class="math inline">\(A\)</span> existe un efecto periodo cuyo valor en <code>logits</code> es -0.49. Es decir, que la valoración del subtitulado de nivel <span class="math inline">\(A\)</span> es inferior en el segundo periodo que en el primero. En la <a href="#fig-probs-clm-treat.period">Figura&nbsp;<span>8.4</span></a> podemos ver las predicciones del modelo.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-probs-clm-treat.period" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="43-Modelado_files/figure-html/fig-probs-clm-treat.period-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8.4: Probabilidades de respuesta para el modelo ordinal Response ~ Treat * Period</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="elección-del-modelo-ordinal-mediante-el-test-de-razón-de-verosimilitud." class="level3" data-number="8.2.5">
<h3 data-number="8.2.5" class="anchored" data-anchor-id="elección-del-modelo-ordinal-mediante-el-test-de-razón-de-verosimilitud."><span class="header-section-number">8.2.5</span> Elección del modelo ordinal mediante el test de razón de verosimilitud.</h3>
<p>Al ser los tres modelos anidados, podemos compararlos con la prueba de razón de verosimilitud. Comprobamos que el tercer modelo (el que incorpora la interacción entre los subtítulos y el periodo) reduce significativamente el logaritmo de la función de verosimilitud y, por lo tanto, debe ser aceptado:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(clm_treat, clm_treat_period, clm_treat.period)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of cumulative link models:
 
                 formula:                  link: threshold:
clm_treat        Response ~ Treat          logit flexible  
clm_treat_period Response ~ Treat + Period logit flexible  
clm_treat.period Response ~ Treat * Period logit flexible  

                 no.par    AIC  logLik LR.stat df Pr(&gt;Chisq)    
clm_treat             5 7942.2 -3966.1                          
clm_treat_period      6 7927.8 -3957.9  16.448  1      5e-05 ***
clm_treat.period      7 7920.0 -3953.0   9.738  1   0.001805 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="comprobación-de-las-hipótesis-del-modelo." class="level3" data-number="8.2.6">
<h3 data-number="8.2.6" class="anchored" data-anchor-id="comprobación-de-las-hipótesis-del-modelo."><span class="header-section-number">8.2.6</span> Comprobación de las hipótesis del modelo.</h3>
<p>La principal hipótesis de un modelo de regresión logística ordinal proporcional acumulativa es que los coeficientes son iguales entre cualesquiera dos niveles de respuestas correlativos. Se han propuesto diversas fórmulas para comprobar esta hipótesis. El paquete <code>Ordinal</code> dispone de la función <code>nominal_test()</code> que lo que hace es realizar un test de razón de verosimilitud para cada predictor ajustando un modelo en el que se ha relajado la condición de proporcionalidad. Se constata que el test resulta significativo para <code>Treat</code> y para <code>Treat:Period</code>, por lo que para estas dos variables no se puede asumir que los coeficientes estimados se mantengan constantes en todos los niveles de respuesta.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nominal_test</span>(clm_treat.period)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Tests of nominal effects

formula: Response ~ Treat * Period
             Df  logLik    AIC     LRT Pr(&gt;Chi)    
&lt;none&gt;          -3953.0 7920.0                     
Treat         3 -3904.4 7828.9  97.172   &lt;2e-16 ***
Period        3 -3951.4 7922.7   3.307   0.3467    
Treat:Period  9 -3884.8 7801.6 136.408   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Lo que procede es ajustar el modelo relajando la constante de proporcionalidad de esas variables. Se ha realizado esto utilizando la función <code>vglm</code> del paquete <code>VGAM</code>. Vemos que ahora hay cuatro coeficientes para cada una de las variables <code>Treat</code> y <code>Treat:Period</code> <a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>vglm_treat.period <span class="ot">&lt;-</span> <span class="fu">vglm</span>(</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    Response <span class="sc">~</span> Treat <span class="sc">*</span> Period,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    VGAM<span class="sc">::</span><span class="fu">cumulative</span>(<span class="at">link =</span> <span class="st">"logit"</span>, <span class="at">parallel =</span> F <span class="sc">~</span> Treat <span class="sc">+</span> Treat<span class="sc">:</span>Period, <span class="at">reverse =</span> T),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> df_clean</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(vglm_treat.period) <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          .
(Intercept):1     6.2295614
(Intercept):2     3.5001281
(Intercept):3     2.2121438
(Intercept):4     0.2998788
TreatB:1         -4.0441016
TreatB:2         -2.8029889
TreatB:3         -2.2174630
TreatB:4         -1.7926200
Period2          -0.5345919
TreatB:Period2:1  0.3509228
TreatB:Period2:2  0.3607009
TreatB:Period2:3  0.3891474
TreatB:Period2:4  0.8024952</code></pre>
</div>
</div>
<p>En la <a href="#fig-probs-vglm-treat.period">Figura&nbsp;<span>8.5</span></a> se muestran las probabilidades de respuesta de este modelo.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-probs-vglm-treat.period" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="43-Modelado_files/figure-html/fig-probs-vglm-treat.period-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8.5: Probabilidades de respuesta para el modelo ordinal no proporcional Response ~ Treat * Period</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="introducción-a-los-modelos-multinivel." class="level3" data-number="8.2.7">
<h3 data-number="8.2.7" class="anchored" data-anchor-id="introducción-a-los-modelos-multinivel."><span class="header-section-number">8.2.7</span> Introducción a los modelos multinivel.</h3>
<p>Un modelo multinivel, jerárquico o mixto es un modelo en el que tenemos datos de un nivel inferior anidados en estructuras de un nivel superior. Por ejemplo, si quisiéramos evaluar el rendimiento de varios métodos de enseñanza, poríamos seleccionar aleatoriamente varios colegios participantes y en cada uno de ellos elegir varias clases en las que se impartiría uno de los métodos de enseñanza. Los modelos multinivel se utilizan cuando se incumple la hipótesis de independencia de entre las observaciones. En el caso de los métodos de enseñanza, los alumnos de una clase no son independientes de los alumnos de otra clase del mismo colegio y también es esperable que los alumnos de un mismo colegio sean más parecidos entre sí que los de otro colegio. Otra situación en la que se viola la condición de independencia entre observaciones es cuando se toman varias medidas del mismo sujeto. Este tipo de experimentos se llaman de medidas repetidas o longitudinales. En este caso se considera que las medidas están anidadas en el sujeto <span class="citation" data-cites="Liu2202">(ver <a href="99-Referencias.html#ref-Liu2202" role="doc-biblioref">Liu 2022</a>)</span>. En un modelo multinivel no es necesario que todas las variables tengan una estructura jerárquica. Distinguimos entonces dos tipos de variables. Las conocidas como de efectos fijos son aquellas variables que se consideran que tienen el mismo efecto en toda la población y, por lo tanto, estimamos un único coeficiente. Las que llamamos como variables de efectos aleatorios tienen un coeficiente diferente para cada elemento de la población y se supone que son una muestra de una población mucho mayor, como el caso de seleccionar aleatoriamente una muestra de colegios. Normalmente el coeficiente particular de cada elemento no es de interés para el investigador y se asuma que tienen una media centrada en cero. El mayor interés de los efectos aleatorios es la estimación de su matriz de varianzas-covarianzas.</p>
<p>La ecuación general de un modelo multinivel con dos niveles y un solo predictor con efectos aleatorios es <span class="citation" data-cites="chen2021">(ver <a href="99-Referencias.html#ref-chen2021" role="doc-biblioref">Chen y Chen 2021, 40</a>)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
Level\ 1: &amp; y_{ij}     &amp; = &amp; \beta_{0j} + \beta_{1j}x_{1ij} + \epsilon_{ij} \\
Level\ 2: &amp; \beta_{0j} &amp; = &amp; \beta_{0} + U_{0j} &amp; (intercepto\ aleatorio) \\
          &amp; \beta_{1j} &amp; = &amp; \beta_{0} + U_{1j} &amp; (pendiente\ aleatoria) \\
\end{aligned}
\]</span></p>
<p>Donde los errores del modelo se distribuyen,</p>
<p><span class="math display">\[
Error\ intra\ grupo:  \epsilon_{ij} \sim N(0, \sigma^2)
\]</span></p>
<p><span class="math display">\[
Error\ entre\ grupos:
\begin{pmatrix}
     U_{0j} \\
     U_{1j} \\
\end{pmatrix}
\sim
N
\begin{pmatrix}
\begin{pmatrix}
     0 \\
     0 \\
\end{pmatrix},
\begin{pmatrix}
     \tau_0^2 &amp; \tau_0\tau_1\rho_{01} \\
     \tau_0\tau_1\rho_{01} &amp;  \tau_1^2 \\
\end{pmatrix}
\end{pmatrix}
\]</span></p>
<p>donde <span class="math inline">\(j\)</span> son los grupos que varían <span class="math inline">\(j = 1,...,J\)</span> (<span class="math inline">\(J\)</span> es el número de grupos); <span class="math inline">\(i\)</span> es la observación <span class="math inline">\(i\)</span> del grupo <span class="math inline">\(j\)</span> (<span class="math inline">\(i = 1,...,n_j\)</span>, <span class="math inline">\(n_j\)</span> es el número de observaciones del grupo <span class="math inline">\(j\)</span>). El modelo se compone de una parte fija <span class="math inline">\(\beta_0 + \beta_1 x_{ij}\)</span> y una aleatoria <span class="math inline">\(U_{0j} + U_{1j} x_{1ij} + \epsilon{ij}\)</span>. Los parámetros de este modelo son el intercepto y la pendiente de efectos fijos (<span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span>), la varianza intra-grupos (<span class="math inline">\(\sigma^2\)</span>), la varianza inter-grupos del intercepto aleatoria (<span class="math inline">\(\tau_0\)</span>) y de la pendiente aleatoria (<span class="math inline">\(\tau_1\)</span>), y la correlación entre intercepto y pendiente aleatorias (<span class="math inline">\(\rho_{01}\)</span>). Cuando se introduce una estructura multinivel se pueden omitir tanto el intercepto como la pendiente aleatoria.</p>
<p>En <span class="citation" data-cites="gelman2013">Gelman et&nbsp;al. (<a href="99-Referencias.html#ref-gelman2013" role="doc-biblioref">2013</a>)</span> se evalúan tres posibilidades a la hora de definir un modelo:</p>
<ul>
<li><span class="math inline">\(Complete\ pooloing\)</span>: Consiste en estimar un único parámetro para cada predictor. Es equivalente a un modelo con efectos fijos.</li>
<li><span class="math inline">\(No\ pooling\)</span>: Se estiman tantos paŕametros como grupos haya de forma independiente.</li>
<li><span class="math inline">\(Partial\ pooling\)</span>: Es el modelo jerárquico. Es una mezcla de ambos, ya que aunque se estima un parámetro para cada grupo, esta estimación no es independiente, sino que se supone que las observaciones de un mismo grupo proceden de una misma distribución de probabilidad. Esto se traduce en que se produce una contracción (<span class="math inline">\(shrinkage\)</span>) en la estimación de los parámetros. Al influir la estimación de unas observaciones en otras, la estimación es de menor valor absoluto que la que resultaría en un modelo de <span class="math inline">\(no\ pooling\)</span>. De esta forma podemos ver el <span class="math inline">\(complete\ pooling\)</span> y el <span class="math inline">\(no\ pooling\)</span> como dos casos particulares y extremos del <span class="math inline">\(no\ pooling\)</span>. La contracción de coeficientes en los modelos multinivel actúa como una regularización que puede evitar el sobreajuste.</li>
</ul>
<p>Los modelos multinivel requieren supuestos adicionales en el nivel segundo y superiores que son similares a los supuestos para los modelos de efectos fijos en el primer y único nivel <span class="citation" data-cites="chen2021">(ver <a href="99-Referencias.html#ref-chen2021" role="doc-biblioref">Chen y Chen 2021, 43</a>)</span>. Para estimar los parámetros en un modelo multinivel se suele utilizar el método de máxima verosimilitud restringida (RMLE), que es una variante de la estimación por máxima verosimilitud (MLE) en la que se hacen ajustes en los grados de libertad del modelo con efectos aleatorios.</p>
</section>
<section id="ajuste-del-modelo-multinivel-ordinal." class="level3" data-number="8.2.8">
<h3 data-number="8.2.8" class="anchored" data-anchor-id="ajuste-del-modelo-multinivel-ordinal."><span class="header-section-number">8.2.8</span> Ajuste del modelo multinivel ordinal.</h3>
<p>El modelo multinivel aleatorio más simple que podemos considerar es el que incorpora únicamente un interceptor aleatorio para los estudiantes del curso. Que los estudiantes sean considerados un efecto aleatorio está doblemente justificado. Por un lado, son una muestra de una población más amplia que estaría constituida por todos los estudiantes de todos los cursos de accesibilidad. Por otro, cada estudiante realiza el test de evaluación dos veces y, por lo tanto, las respuestas a estos cuestionarios no son independientes. La especificación del modelo será la siguiente:</p>
<p><span class="math display">\[
\text{logit}(P(Response_{ij} \leq k)) = \tau_k +\tau_{kj} - \beta_1 \text{Treat}_{ij},
\]</span></p>
<p>donde <span class="math inline">\(Response_{ij}\)</span> es la observación <span class="math inline">\(i\)</span> del usuario <span class="math inline">\(j\)</span>, <span class="math inline">\(\tau_k\)</span> es el interceptor común a todos los usuarios para el nivel de respuesta <span class="math inline">\(k\)</span> y <span class="math inline">\(\tau_{kj}\)</span> es el interceptor específico para el usuario <span class="math inline">\(j\)</span>. Para ajustar el modelo, vamos a utilizar la función <code>clmm()</code> del paquete <code>Ordinal</code> ya que permite la inclusión de efectos aleatorios.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>clmm_subject <span class="ot">&lt;-</span> <span class="fu">clmm</span>(Response <span class="sc">~</span> (<span class="dv">1</span> <span class="sc">|</span> Subject), <span class="at">data =</span> df_clean)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clmm_subject)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cumulative Link Mixed Model fitted with the Laplace approximation

formula: Response ~ (1 | Subject)
data:    df_clean

 link  threshold nobs logLik   AIC     niter     max.grad cond.H 
 logit flexible  2980 -4053.61 8117.23 272(1093) 7.11e-04 8.3e+01

Random effects:
 Groups  Name        Variance Std.Dev.
 Subject (Intercept) 0.8385   0.9157  
Number of groups:  Subject 87 

No Coefficients

Threshold coefficients:
    Estimate Std. Error z value
1|2  -3.1597     0.1291 -24.481
2|3  -1.6869     0.1109 -15.212
3|4  -0.9383     0.1077  -8.713
4|5   0.6354     0.1068   5.951</code></pre>
</div>
</div>
<p>Vemos que el parámetro <span class="math inline">\(\widehat{\tau_0}\)</span> tiene un valor 0.92 y que no hay coeficientes que estimar. El siguiente modelo en orden de complejidad es el que incorpora el predictor <code>Treat</code>:</p>
<div class="cell" data-hash="43-Modelado_cache/html/unnamed-chunk-29_7d94d683715f8f142f52807028c2c5d2">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>clmm_treat_subject <span class="ot">&lt;-</span> <span class="fu">clmm</span>(Response <span class="sc">~</span> Treat <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Subject), <span class="at">data =</span> df_clean)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clmm_treat_subject)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cumulative Link Mixed Model fitted with the Laplace approximation

formula: Response ~ Treat + (1 | Subject)
data:    df_clean

 link  threshold nobs logLik   AIC     niter     max.grad cond.H 
 logit flexible  2980 -3665.73 7343.47 395(1585) 4.97e-04 9.5e+01

Random effects:
 Groups  Name        Variance Std.Dev.
 Subject (Intercept) 1.265    1.125   
Number of groups:  Subject 87 

Coefficients:
       Estimate Std. Error z value Pr(&gt;|z|)    
TreatB  -2.0747     0.0793  -26.16   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
    Estimate Std. Error z value
1|2  -4.7243     0.1638 -28.839
2|3  -3.0518     0.1453 -21.008
3|4  -2.1256     0.1392 -15.269
4|5  -0.2068     0.1325  -1.561</code></pre>
</div>
</div>
<p>En este modelo <span class="math inline">\(\widehat{\tau_0}\)</span> vale 1.12 y la pendiente del tratamiento, <code>TreatB</code> es -2.07. Podemos considerar un modelo en la que la valoración de cada sujeto sea diferente para cada tratamiento:</p>
<div class="cell" data-hash="43-Modelado_cache/html/unnamed-chunk-30_8013642ad8bc1d19295dc64dc33464ee">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>clmm_treat.subject <span class="ot">&lt;-</span> <span class="fu">clmm</span>(Response <span class="sc">~</span> Treat <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Treat <span class="sc">|</span> Subject), <span class="at">data =</span> df_clean)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clmm_treat.subject)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cumulative Link Mixed Model fitted with the Laplace approximation

formula: Response ~ Treat + (1 + Treat | Subject)
data:    df_clean

 link  threshold nobs logLik   AIC     niter     max.grad cond.H 
 logit flexible  2980 -3431.27 6878.53 535(3741) 2.43e-03 1.7e+02

Random effects:
 Groups  Name        Variance Std.Dev. Corr   
 Subject (Intercept) 2.691    1.641           
         TreatB      4.295    2.072    -0.598 
Number of groups:  Subject 87 

Coefficients:
       Estimate Std. Error z value Pr(&gt;|z|)    
TreatB  -2.5864     0.2425  -10.67   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
    Estimate Std. Error z value
1|2  -5.5561     0.2207 -25.173
2|3  -3.6249     0.2024 -17.914
3|4  -2.5581     0.1968 -12.999
4|5  -0.3271     0.1900  -1.721</code></pre>
</div>
</div>
<p>Ahora <span class="math inline">\(\widehat{\tau_0}\)</span> vale 1.64 y <span class="math inline">\(\widehat{\tau_1}\)</span> 2.07. La correlación, <span class="math inline">\(\rho_{01}\)</span>, es -0.6. Podemos añadir el factor <code>Period</code> al modelo:</p>
<div class="cell" data-hash="43-Modelado_cache/html/unnamed-chunk-31_9286e91c15db4fd144b8be7420e75437">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>clmm_treat.period.subject <span class="ot">&lt;-</span> <span class="fu">clmm</span>(</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    Response <span class="sc">~</span> Treat <span class="sc">*</span> Period <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Treat <span class="sc">|</span> Subject),</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> df_clean</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clmm_treat.period.subject)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cumulative Link Mixed Model fitted with the Laplace approximation

formula: Response ~ Treat * Period + (1 + Treat | Subject)
data:    df_clean

 link  threshold nobs logLik   AIC     niter       max.grad cond.H 
 logit flexible  2980 -3429.88 6879.76 1696(11676) 7.34e-05 6.4e+02

Random effects:
 Groups  Name        Variance Std.Dev. Corr   
 Subject (Intercept) 2.588    1.609           
         TreatB      4.168    2.042    -0.584 
Number of groups:  Subject 87 

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
TreatB          -2.8530     0.3795  -7.519 5.53e-14 ***
Period2         -0.5893     0.3685  -1.599    0.110    
TreatB:Period2   0.5307     0.5855   0.906    0.365    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
    Estimate Std. Error z value
1|2  -5.8518     0.2892 -20.236
2|3  -3.9206     0.2754 -14.234
3|4  -2.8541     0.2714 -10.515
4|5  -0.6226     0.2654  -2.345</code></pre>
</div>
</div>
<p>Vemos que, a diferencia de lo que sucedía en el modelo de efectos fijos, el periodo y la interacción del periodo con el subtitulado son ahora no significativos. Queda, por último, discutir cómo añadir las preguntas al modelo. Consideramos que las respuestas a las preguntas no son independientes unas de otras y que, por lo tanto, deben ser consideradas efectos aleatorios. En <span class="citation" data-cites="burkner2021">Bürkner (<a href="99-Referencias.html#ref-burkner2021" role="doc-biblioref">2021</a>)</span> <span class="citation" data-cites="burkner2019">Bürkner y Vuorre (<a href="99-Referencias.html#ref-burkner2019" role="doc-biblioref">2019, 19-20</a>)</span> podemos encontrar un ejemplo de esta solución. Las preguntas como efecto aleatorio se pueden añadir considerando únicamente el intercepto o el intercepto y la pendiente. Ajustamos ambos modelos:</p>
<div class="cell" data-hash="43-Modelado_cache/html/unnamed-chunk-32_244d508022465a7eaa703d1207d7ad22">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>clmm_treat.period.subject_question <span class="ot">&lt;-</span> <span class="fu">clmm</span>(</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>    Response <span class="sc">~</span> Treat <span class="sc">*</span> Period <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Treat <span class="sc">|</span> Subject) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Question),</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> df_clean</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clmm_treat.period.subject_question)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cumulative Link Mixed Model fitted with the Laplace approximation

formula: Response ~ Treat * Period + (1 + Treat | Subject) + (1 | Question)
data:    df_clean

 link  threshold nobs logLik   AIC     niter     max.grad cond.H 
 logit flexible  2980 -3309.04 6640.07 960(7467) 3.85e-04 6.6e+02

Random effects:
 Groups   Name        Variance Std.Dev. Corr   
 Subject  (Intercept) 3.0249   1.739           
          TreatB      4.8228   2.196    -0.591 
 Question (Intercept) 0.4651   0.682           
Number of groups:  Subject 87,  Question 18 

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
TreatB          -3.0562     0.4062  -7.525 5.29e-14 ***
Period2         -0.6163     0.3966  -1.554    0.120    
TreatB:Period2   0.5608     0.6266   0.895    0.371    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
    Estimate Std. Error z value
1|2  -6.2609     0.3506 -17.858
2|3  -4.1977     0.3375 -12.439
3|4  -3.0366     0.3334  -9.108
4|5  -0.6370     0.3276  -1.944</code></pre>
</div>
</div>
<div class="cell" data-hash="43-Modelado_cache/html/unnamed-chunk-33_bf76d8057fca187a5a33084a97910137">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>clmm_treat.period.subject.question <span class="ot">&lt;-</span> <span class="fu">clmm</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>    Response <span class="sc">~</span> Treat <span class="sc">*</span> Period <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Treat <span class="sc">|</span> Subject) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Treat <span class="sc">|</span> Question),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> df_clean</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clmm_treat.period.subject.question)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cumulative Link Mixed Model fitted with the Laplace approximation

formula: Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat |  
    Question)
data:    df_clean

 link  threshold nobs logLik   AIC     niter      max.grad cond.H 
 logit flexible  2980 -3186.06 6398.11 1026(8128) 1.80e-04 6.1e+02

Random effects:
 Groups   Name        Variance Std.Dev. Corr   
 Subject  (Intercept) 3.1372   1.7712          
          TreatB      5.4601   2.3367   -0.552 
 Question (Intercept) 0.4474   0.6689          
          TreatB      1.8621   1.3646   -0.471 
Number of groups:  Subject 87,  Question 18 

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
TreatB          -3.1435     0.5358  -5.867 4.43e-09 ***
Period2         -0.6255     0.4028  -1.553    0.120    
TreatB:Period2   0.5590     0.6615   0.845    0.398    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
    Estimate Std. Error z value
1|2  -6.7481     0.3585 -18.821
2|3  -4.3947     0.3411 -12.884
3|4  -3.1106     0.3362  -9.252
4|5  -0.5610     0.3298  -1.701</code></pre>
</div>
</div>
<p>Un modelo más simple que el anterior que podemos considerar es eliminar la pendiente del subtitulado en el efecto aleatorio <code>Subject</code>.</p>
<div class="cell" data-hash="43-Modelado_cache/html/unnamed-chunk-34_1a0871de819179731670b9c73df0f12a">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>clmm_treat.period_subject_question <span class="ot">&lt;-</span> <span class="fu">clmm</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>    Response <span class="sc">~</span> Treat <span class="sc">*</span> Period <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Subject) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Question),</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> df_clean</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clmm_treat.period_subject_question)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cumulative Link Mixed Model fitted with the Laplace approximation

formula: Response ~ Treat * Period + (1 | Subject) + (1 | Question)
data:    df_clean

 link  threshold nobs logLik   AIC     niter     max.grad cond.H 
 logit flexible  2980 -3559.48 7136.96 987(3952) 5.50e-04 5.9e+02

Random effects:
 Groups   Name        Variance Std.Dev.
 Subject  (Intercept) 1.4348   1.1978  
 Question (Intercept) 0.3394   0.5826  
Number of groups:  Subject 87,  Question 18 

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
TreatB          -2.5366     0.2815  -9.012   &lt;2e-16 ***
Period2         -0.6203     0.2795  -2.219   0.0265 *  
TreatB:Period2   0.5958     0.5353   1.113   0.2657    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
    Estimate Std. Error z value
1|2  -5.3264     0.2655 -20.059
2|3  -3.5644     0.2530 -14.089
3|4  -2.5690     0.2488 -10.325
4|5  -0.5243     0.2434  -2.154</code></pre>
</div>
</div>
<p>E incluso eliminar completamente el efecto aleatorio <code>Subject</code> y mantener solo las preguntas como efecto aleatorio.</p>
<div class="cell" data-hash="43-Modelado_cache/html/unnamed-chunk-35_20eb1e7477280d0774e20bbd42a95107">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>clmm_treat.period_question <span class="ot">&lt;-</span> <span class="fu">clmm</span>(</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>    Response <span class="sc">~</span> Treat <span class="sc">*</span> Period <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Question),</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> df_clean</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clmm_treat.period_question)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cumulative Link Mixed Model fitted with the Laplace approximation

formula: Response ~ Treat * Period + (1 | Question)
data:    df_clean

 link  threshold nobs logLik   AIC     niter     max.grad cond.H 
 logit flexible  2980 -3883.04 7782.07 741(2226) 1.08e-04 1.3e+02

Random effects:
 Groups   Name        Variance Std.Dev.
 Question (Intercept) 0.2274   0.4769  
Number of groups:  Question 18 

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
TreatB         -2.04502    0.10378 -19.706  &lt; 2e-16 ***
Period2        -0.50200    0.09929  -5.056 4.29e-07 ***
TreatB:Period2  0.43361    0.13747   3.154  0.00161 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Threshold coefficients:
    Estimate Std. Error z value
1|2  -4.4008     0.1610 -27.337
2|3  -2.8298     0.1446 -19.575
3|4  -1.9983     0.1401 -14.259
4|5  -0.3609     0.1349  -2.675</code></pre>
</div>
</div>
<p>Mediante el test de razón de verosimilitud podemos seleccionar el modelo con menor función de verosimilitud:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>    clmm_subject,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    clmm_treat.subject,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    clmm_treat.period.subject,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    clmm_treat.period.subject_question,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    clmm_treat.period.subject.question,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    clmm_treat.period_subject_question,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>    clmm_treat.period_question</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Likelihood ratio tests of cumulative link models:
 
                                   formula:                                                                  
clmm_subject                       Response ~ (1 | Subject)                                                  
clmm_treat.subject                 Response ~ Treat + (1 + Treat | Subject)                                  
clmm_treat.period_question         Response ~ Treat * Period + (1 | Question)                                
clmm_treat.period_subject_question Response ~ Treat * Period + (1 | Subject) + (1 | Question)                
clmm_treat.period.subject          Response ~ Treat * Period + (1 + Treat | Subject)                         
clmm_treat.period.subject_question Response ~ Treat * Period + (1 + Treat | Subject) + (1 | Question)        
clmm_treat.period.subject.question Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Question)
                                   link: threshold:
clmm_subject                       logit flexible  
clmm_treat.subject                 logit flexible  
clmm_treat.period_question         logit flexible  
clmm_treat.period_subject_question logit flexible  
clmm_treat.period.subject          logit flexible  
clmm_treat.period.subject_question logit flexible  
clmm_treat.period.subject.question logit flexible  

                                   no.par    AIC  logLik LR.stat df Pr(&gt;Chisq)
clmm_subject                            5 8117.2 -4053.6                      
clmm_treat.subject                      8 6878.5 -3431.3 1244.69  3  &lt; 2.2e-16
clmm_treat.period_question              8 7782.1 -3883.0 -903.54  0           
clmm_treat.period_subject_question      9 7137.0 -3559.5  647.12  1  &lt; 2.2e-16
clmm_treat.period.subject              10 6879.8 -3429.9  259.20  1  &lt; 2.2e-16
clmm_treat.period.subject_question     11 6640.1 -3309.0  241.69  1  &lt; 2.2e-16
clmm_treat.period.subject.question     13 6398.1 -3186.1  245.96  2  &lt; 2.2e-16
                                      
clmm_subject                          
clmm_treat.subject                 ***
clmm_treat.period_question            
clmm_treat.period_subject_question ***
clmm_treat.period.subject          ***
clmm_treat.period.subject_question ***
clmm_treat.period.subject.question ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Vemos que el modelo más complejo, <code>clmm_treat.period.subject.question</code>, presenta una menor funcion de verosimilitud. Este modelo tiene un <span class="math inline">\(AIC\)</span> menor que los modelos ordinales ajustados en el apartado anterior incluso si a esos modelos se les añade como factor predictor <code>Question</code>. En el <a href="#tbl-question-intercepts">Tabla&nbsp;<span>8.2</span></a> se muestran los interceptores y pendientes estimadas para el efecto aleatorio <code>Question</code>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-question-intercepts" class="anchored">
<table class="table table-sm table-striped small">
<caption>Tabla&nbsp;8.2: Intercepto y pendiente de Question en el modelo Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Question)</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">(Intercept)</th>
<th style="text-align: right;">TreatB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Q18</td>
<td style="text-align: right;">0.3933757</td>
<td style="text-align: right;">-1.1021051</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q01</td>
<td style="text-align: right;">0.2726623</td>
<td style="text-align: right;">0.4752429</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q02</td>
<td style="text-align: right;">0.6197324</td>
<td style="text-align: right;">-0.3813147</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q03</td>
<td style="text-align: right;">0.0640464</td>
<td style="text-align: right;">0.5063518</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q04</td>
<td style="text-align: right;">0.5020005</td>
<td style="text-align: right;">1.9203520</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q05</td>
<td style="text-align: right;">0.7498895</td>
<td style="text-align: right;">-2.8118058</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q06</td>
<td style="text-align: right;">0.5528685</td>
<td style="text-align: right;">-0.8949249</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q07</td>
<td style="text-align: right;">-0.0106860</td>
<td style="text-align: right;">-0.4533266</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q08</td>
<td style="text-align: right;">-0.1980169</td>
<td style="text-align: right;">-0.8402323</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q09</td>
<td style="text-align: right;">0.0184714</td>
<td style="text-align: right;">-2.4698505</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q10</td>
<td style="text-align: right;">0.0228628</td>
<td style="text-align: right;">0.1615350</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q11</td>
<td style="text-align: right;">0.0782894</td>
<td style="text-align: right;">0.6223213</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q12</td>
<td style="text-align: right;">-0.2003100</td>
<td style="text-align: right;">0.3403381</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q13</td>
<td style="text-align: right;">0.5516281</td>
<td style="text-align: right;">1.5330216</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q14</td>
<td style="text-align: right;">-0.2392607</td>
<td style="text-align: right;">-0.4339893</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q15</td>
<td style="text-align: right;">-1.3380683</td>
<td style="text-align: right;">1.4804380</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Q16</td>
<td style="text-align: right;">-1.3655878</td>
<td style="text-align: right;">1.7228905</td>
</tr>
<tr class="even">
<td style="text-align: left;">Q17</td>
<td style="text-align: right;">-1.0044586</td>
<td style="text-align: right;">1.1760588</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Las preguntas Q16, Q15, Q17, Q05, Q02 son las 5 cuyo <code>log odds</code> del intercepto tiene un valor mayor valor absoluto y, por lo tanto, las que nuestro modelo considera más diferentes del resto. Por otro lado, las preguntas Q05, Q09, Q04, Q16, Q13 son las que mayor valor absoluto tienen en el coeficiente <code>TreatB</code> y, por ello, las que presentan mayor diferencia entre tratamientos. En la <a href="#fig-probs-clmm_treat.period.subject.question">Figura&nbsp;<span>8.6</span></a> se muestran las predicciones del modelo.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-probs-clmm_treat.period.subject.question" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="43-Modelado_files/figure-html/fig-probs-clmm_treat.period.subject.question-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8.6: Probabilidades de respuesta para el modelo ordinal Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Question)</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="modelado-bayesiano." class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="modelado-bayesiano."><span class="header-section-number">8.3</span> Modelado Bayesiano.</h2>
<p>En el apéndice (ver <a href="78-Bayesiano.html"><span>Apéndice&nbsp;D</span></a>) se comparan diversas parametrizaciones de modelado bayesiano utilizando la función <code>brm()</code> del paquete <code>brms</code>. Analizamos aquí la que mejor resultado produjo con la validación cruzada bayesiana <code>leave-one-out</code>:</p>
<div class="cell" data-hash="43-Modelado_cache/html/unnamed-chunk-39_524eace367d29e58ded83f41b69e33c9">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>brm_treat.period.subject.question <span class="ot">&lt;-</span> <span class="fu">brm</span>(</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>    Response <span class="sc">~</span> Treat <span class="sc">*</span> Period <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Treat <span class="sc">|</span> Subject) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Treat <span class="sc">|</span> Question),</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> df_clean,</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="fu">cumulative</span>(<span class="st">"logit"</span>),</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sample_prior =</span> <span class="cn">TRUE</span>,</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">file =</span> <span class="st">"models/brm_treat.period.subject.question"</span>,</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">file_refit =</span> <span class="st">"on_change"</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Esta parametrización coincide con la que elegimos en el apartado de Regresión Ordinal con efectos mixtos. El modelo utiliza como factores con efectos fijos (<code>complete pooling</code> en terminología bayesiana) el nivel de subtitulado y el periodo y la interacción entre ambos; y como efectos aleatorios (<code>partial pooling</code>) los sujetos y las preguntas del test. Cada uno de ellos con un intercepto y un nivel de subtitulado variable. El resumen del modelo es el siguiente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(brm_treat.period.subject.question)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: cumulative 
  Links: mu = logit; disc = identity 
Formula: Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Question) 
   Data: df_clean (Number of observations: 2980) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Group-Level Effects: 
~Question (Number of levels: 18) 
                      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS
sd(Intercept)             0.74      0.16     0.50     1.11 1.00     1213
sd(TreatB)                1.50      0.29     1.05     2.21 1.00     1194
cor(Intercept,TreatB)    -0.41      0.21    -0.74     0.07 1.01      931
                      Tail_ESS
sd(Intercept)             2155
sd(TreatB)                1803
cor(Intercept,TreatB)     1691

~Subject (Number of levels: 87) 
                      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS
sd(Intercept)             1.82      0.18     1.50     2.21 1.00      841
sd(TreatB)                2.39      0.21     2.01     2.84 1.00      685
cor(Intercept,TreatB)    -0.54      0.09    -0.70    -0.35 1.01      420
                      Tail_ESS
sd(Intercept)             1266
sd(TreatB)                1487
cor(Intercept,TreatB)      719

Population-Level Effects: 
               Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept[1]      -6.70      0.37    -7.43    -5.98 1.00      701     1417
Intercept[2]      -4.35      0.35    -5.03    -3.64 1.00      641     1231
Intercept[3]      -3.06      0.34    -3.73    -2.37 1.00      626     1271
Intercept[4]      -0.50      0.34    -1.17     0.18 1.00      623     1227
TreatB            -3.15      0.57    -4.28    -2.04 1.01      483     1112
Period2           -0.58      0.41    -1.41     0.21 1.01      492      943
TreatB:Period2     0.50      0.68    -0.82     1.83 1.00      428      888

Family Specific Parameters: 
     Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
disc     1.00      0.00     1.00     1.00   NA       NA       NA

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).</code></pre>
</div>
</div>
<p>En la <a href="#tbl-model-comp">Tabla&nbsp;<span>8.3</span></a> se comparan las estimaciones puntuales que obtuvimos para este modelo con la función <code>clmm</code> para ajustar el modelo con efectos mixtos. Se comprueba que son muy similares. Vemos que los interceptores son claramente significativos y también el coeficiente de <code>TreatB</code>. Sin embargo los coeficientes correspondientes al efecto periodo, <code>Period2</code>, y al efecto secuencia, <code>TreatB:Period</code>, incluyen el cero y además tienen intervalos muy grandes por lo que hay mucha incertidumbre respecto a su verdadero valor.</p>
<div class="cell" data-hash="43-Modelado_cache/html/tbl-model-comp_eb4a190be52142a0a750f06ceec139b9">
<div class="cell-output-display">

<div id="pcnrbwykdt" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#pcnrbwykdt .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 6px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#pcnrbwykdt .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pcnrbwykdt .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#pcnrbwykdt .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#pcnrbwykdt .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#pcnrbwykdt .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pcnrbwykdt .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pcnrbwykdt .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#pcnrbwykdt .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#pcnrbwykdt .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#pcnrbwykdt .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#pcnrbwykdt .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#pcnrbwykdt .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#pcnrbwykdt .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#pcnrbwykdt .gt_from_md > :first-child {
  margin-top: 0;
}

#pcnrbwykdt .gt_from_md > :last-child {
  margin-bottom: 0;
}

#pcnrbwykdt .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#pcnrbwykdt .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#pcnrbwykdt .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#pcnrbwykdt .gt_row_group_first td {
  border-top-width: 2px;
}

#pcnrbwykdt .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pcnrbwykdt .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#pcnrbwykdt .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#pcnrbwykdt .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pcnrbwykdt .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pcnrbwykdt .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#pcnrbwykdt .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#pcnrbwykdt .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pcnrbwykdt .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pcnrbwykdt .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pcnrbwykdt .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pcnrbwykdt .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pcnrbwykdt .gt_left {
  text-align: left;
}

#pcnrbwykdt .gt_center {
  text-align: center;
}

#pcnrbwykdt .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#pcnrbwykdt .gt_font_normal {
  font-weight: normal;
}

#pcnrbwykdt .gt_font_bold {
  font-weight: bold;
}

#pcnrbwykdt .gt_font_italic {
  font-style: italic;
}

#pcnrbwykdt .gt_super {
  font-size: 65%;
}

#pcnrbwykdt .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#pcnrbwykdt .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#pcnrbwykdt .gt_indent_1 {
  text-indent: 5px;
}

#pcnrbwykdt .gt_indent_2 {
  text-indent: 10px;
}

#pcnrbwykdt .gt_indent_3 {
  text-indent: 15px;
}

#pcnrbwykdt .gt_indent_4 {
  text-indent: 20px;
}

#pcnrbwykdt .gt_indent_5 {
  text-indent: 25px;
}
</style>

<div id="tbl-model-comp" class="anchored">
<table class="gt_table table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabla&nbsp;8.3: Comparación frecuentista/bayesiano de coeficientes estimados en el modelo Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Question).</caption>
<thead class="gt_col_headings">
<tr class="header">
<th rowspan="2" id="Name" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Name</th>
<th colspan="3" id="ordinal::clmm" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="colgroup"><span class="gt_column_spanner">ordinal::clmm</span></th>
<th colspan="3" id="brms::brm" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" scope="colgroup"><span class="gt_column_spanner">brms::brm</span></th>
</tr>
<tr class="odd">
<th id="Estimation.clmm" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Estimation.clmm</th>
<th id="conf.2.5%" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">conf.2.5%</th>
<th id="conf.97.5%" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">conf.97.5%</th>
<th id="Estimation.brm" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Estimation.brm</th>
<th id="cred.2.5%" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">cred.2.5%</th>
<th id="cred.97.5%" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">cred.97.5%</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Name">1|2</td>
<td class="gt_row gt_right" headers="Estimation.clmm">-6.75</td>
<td class="gt_row gt_right" headers="conf.2.5%">-7.45</td>
<td class="gt_row gt_right" headers="conf.97.5%">-6.05</td>
<td class="gt_row gt_right" headers="Estimation.brm">-6.71</td>
<td class="gt_row gt_right" headers="cred.2.5%">-7.43</td>
<td class="gt_row gt_right" headers="cred.97.5%">-5.98</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Name">2|3</td>
<td class="gt_row gt_right" headers="Estimation.clmm">-4.39</td>
<td class="gt_row gt_right" headers="conf.2.5%">-5.06</td>
<td class="gt_row gt_right" headers="conf.97.5%">-3.73</td>
<td class="gt_row gt_right" headers="Estimation.brm">-4.35</td>
<td class="gt_row gt_right" headers="cred.2.5%">-5.03</td>
<td class="gt_row gt_right" headers="cred.97.5%">-3.64</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Name">3|4</td>
<td class="gt_row gt_right" headers="Estimation.clmm">-3.11</td>
<td class="gt_row gt_right" headers="conf.2.5%">-3.77</td>
<td class="gt_row gt_right" headers="conf.97.5%">-2.45</td>
<td class="gt_row gt_right" headers="Estimation.brm">-3.06</td>
<td class="gt_row gt_right" headers="cred.2.5%">-3.73</td>
<td class="gt_row gt_right" headers="cred.97.5%">-2.37</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Name">4|5</td>
<td class="gt_row gt_right" headers="Estimation.clmm">-0.56</td>
<td class="gt_row gt_right" headers="conf.2.5%">-1.21</td>
<td class="gt_row gt_right" headers="conf.97.5%">0.09</td>
<td class="gt_row gt_right" headers="Estimation.brm">-0.50</td>
<td class="gt_row gt_right" headers="cred.2.5%">-1.17</td>
<td class="gt_row gt_right" headers="cred.97.5%">0.18</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Name">TreatB</td>
<td class="gt_row gt_right" headers="Estimation.clmm">-3.14</td>
<td class="gt_row gt_right" headers="conf.2.5%">-4.19</td>
<td class="gt_row gt_right" headers="conf.97.5%">-2.09</td>
<td class="gt_row gt_right" headers="Estimation.brm">-3.14</td>
<td class="gt_row gt_right" headers="cred.2.5%">-4.28</td>
<td class="gt_row gt_right" headers="cred.97.5%">-2.04</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Name">Period2</td>
<td class="gt_row gt_right" headers="Estimation.clmm">-0.63</td>
<td class="gt_row gt_right" headers="conf.2.5%">-1.42</td>
<td class="gt_row gt_right" headers="conf.97.5%">0.16</td>
<td class="gt_row gt_right" headers="Estimation.brm">-0.57</td>
<td class="gt_row gt_right" headers="cred.2.5%">-1.41</td>
<td class="gt_row gt_right" headers="cred.97.5%">0.21</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Name">TreatB:Period2</td>
<td class="gt_row gt_right" headers="Estimation.clmm">0.56</td>
<td class="gt_row gt_right" headers="conf.2.5%">-0.74</td>
<td class="gt_row gt_right" headers="conf.97.5%">1.86</td>
<td class="gt_row gt_right" headers="Estimation.brm">0.52</td>
<td class="gt_row gt_right" headers="cred.2.5%">-0.82</td>
<td class="gt_row gt_right" headers="cred.97.5%">1.83</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Name">Subject.sd(Intercept)</td>
<td class="gt_row gt_right" headers="Estimation.clmm">0.67</td>
<td class="gt_row gt_right" headers="conf.2.5%"></td>
<td class="gt_row gt_right" headers="conf.97.5%"></td>
<td class="gt_row gt_right" headers="Estimation.brm">0.72</td>
<td class="gt_row gt_right" headers="cred.2.5%">0.50</td>
<td class="gt_row gt_right" headers="cred.97.5%">1.11</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Name">Subject.sd(TreatB)</td>
<td class="gt_row gt_right" headers="Estimation.clmm">1.36</td>
<td class="gt_row gt_right" headers="conf.2.5%"></td>
<td class="gt_row gt_right" headers="conf.97.5%"></td>
<td class="gt_row gt_right" headers="Estimation.brm">1.47</td>
<td class="gt_row gt_right" headers="cred.2.5%">1.05</td>
<td class="gt_row gt_right" headers="cred.97.5%">2.21</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Name">Subject.cor(Intercept,TreatB)</td>
<td class="gt_row gt_right" headers="Estimation.clmm">1.77</td>
<td class="gt_row gt_right" headers="conf.2.5%"></td>
<td class="gt_row gt_right" headers="conf.97.5%"></td>
<td class="gt_row gt_right" headers="Estimation.brm">1.82</td>
<td class="gt_row gt_right" headers="cred.2.5%">1.50</td>
<td class="gt_row gt_right" headers="cred.97.5%">2.21</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Name">Question.sd(Intercept)</td>
<td class="gt_row gt_right" headers="Estimation.clmm">2.34</td>
<td class="gt_row gt_right" headers="conf.2.5%"></td>
<td class="gt_row gt_right" headers="conf.97.5%"></td>
<td class="gt_row gt_right" headers="Estimation.brm">2.38</td>
<td class="gt_row gt_right" headers="cred.2.5%">2.01</td>
<td class="gt_row gt_right" headers="cred.97.5%">2.84</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Name">Question.sd(TreatB)</td>
<td class="gt_row gt_right" headers="Estimation.clmm">-0.47</td>
<td class="gt_row gt_right" headers="conf.2.5%"></td>
<td class="gt_row gt_right" headers="conf.97.5%"></td>
<td class="gt_row gt_right" headers="Estimation.brm">-0.44</td>
<td class="gt_row gt_right" headers="cred.2.5%">-0.74</td>
<td class="gt_row gt_right" headers="cred.97.5%">0.07</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Name">Question.cor(Intercept,TreatB)</td>
<td class="gt_row gt_right" headers="Estimation.clmm">-0.55</td>
<td class="gt_row gt_right" headers="conf.2.5%"></td>
<td class="gt_row gt_right" headers="conf.97.5%"></td>
<td class="gt_row gt_right" headers="Estimation.brm">-0.54</td>
<td class="gt_row gt_right" headers="cred.2.5%">-0.70</td>
<td class="gt_row gt_right" headers="cred.97.5%">-0.35</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<p>Hemos mantenido las distribuciones de probabilidad a priori que por defecto utiliza <code>brm</code> confiando en que sus parámetros son adecuados. Sin embargo, conviene comprobar que realmente sea así. En la <a href="#tbl-priors">Tabla&nbsp;<span>8.4</span></a> se muestran las distribuciones a priori de los parámetros aleatorios del modelo. En la <a href="#fig-priors">Figura&nbsp;<span>8.7</span></a> se constata que toman valores razonables y no informativos.</p>
<div class="cell" data-hash="43-Modelado_cache/html/tbl-priors_924cc88b9e6a3e7264ba6d1705b0d0b0">
<div class="cell-output-display">

<div id="mbduryjjxb" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#mbduryjjxb .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 8px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#mbduryjjxb .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mbduryjjxb .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#mbduryjjxb .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#mbduryjjxb .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#mbduryjjxb .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mbduryjjxb .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mbduryjjxb .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#mbduryjjxb .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#mbduryjjxb .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#mbduryjjxb .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#mbduryjjxb .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#mbduryjjxb .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#mbduryjjxb .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#mbduryjjxb .gt_from_md > :first-child {
  margin-top: 0;
}

#mbduryjjxb .gt_from_md > :last-child {
  margin-bottom: 0;
}

#mbduryjjxb .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#mbduryjjxb .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#mbduryjjxb .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#mbduryjjxb .gt_row_group_first td {
  border-top-width: 2px;
}

#mbduryjjxb .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mbduryjjxb .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#mbduryjjxb .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#mbduryjjxb .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mbduryjjxb .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mbduryjjxb .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#mbduryjjxb .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#mbduryjjxb .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mbduryjjxb .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mbduryjjxb .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#mbduryjjxb .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mbduryjjxb .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#mbduryjjxb .gt_left {
  text-align: left;
}

#mbduryjjxb .gt_center {
  text-align: center;
}

#mbduryjjxb .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#mbduryjjxb .gt_font_normal {
  font-weight: normal;
}

#mbduryjjxb .gt_font_bold {
  font-weight: bold;
}

#mbduryjjxb .gt_font_italic {
  font-style: italic;
}

#mbduryjjxb .gt_super {
  font-size: 65%;
}

#mbduryjjxb .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#mbduryjjxb .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#mbduryjjxb .gt_indent_1 {
  text-indent: 5px;
}

#mbduryjjxb .gt_indent_2 {
  text-indent: 10px;
}

#mbduryjjxb .gt_indent_3 {
  text-indent: 15px;
}

#mbduryjjxb .gt_indent_4 {
  text-indent: 20px;
}

#mbduryjjxb .gt_indent_5 {
  text-indent: 25px;
}
</style>

<div id="tbl-priors" class="anchored">
<table class="gt_table table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabla&nbsp;8.4: Distribuciones a priori del modelo Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Question).</caption>
<thead class="gt_col_headings">
<tr class="header">
<th id="prior" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">prior</th>
<th id="class" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">class</th>
<th id="coef" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">coef</th>
<th id="group" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">group</th>
<th id="resp" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">resp</th>
<th id="dpar" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">dpar</th>
<th id="nlpar" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">nlpar</th>
<th id="lb" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">lb</th>
<th id="ub" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">ub</th>
<th id="source" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">source</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">b</td>
<td class="gt_row gt_left" headers="coef"></td>
<td class="gt_row gt_left" headers="group"></td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">b</td>
<td class="gt_row gt_left" headers="coef">Period2</td>
<td class="gt_row gt_left" headers="group"></td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">b</td>
<td class="gt_row gt_left" headers="coef">TreatB</td>
<td class="gt_row gt_left" headers="group"></td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">b</td>
<td class="gt_row gt_left" headers="coef">TreatB:Period2</td>
<td class="gt_row gt_left" headers="group"></td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="prior">student_t(3, 0, 2.5)</td>
<td class="gt_row gt_left" headers="class">Intercept</td>
<td class="gt_row gt_left" headers="coef"></td>
<td class="gt_row gt_left" headers="group"></td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">Intercept</td>
<td class="gt_row gt_left" headers="coef">1</td>
<td class="gt_row gt_left" headers="group"></td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">Intercept</td>
<td class="gt_row gt_left" headers="coef">2</td>
<td class="gt_row gt_left" headers="group"></td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">Intercept</td>
<td class="gt_row gt_left" headers="coef">3</td>
<td class="gt_row gt_left" headers="group"></td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">Intercept</td>
<td class="gt_row gt_left" headers="coef">4</td>
<td class="gt_row gt_left" headers="group"></td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="prior">lkj_corr_cholesky(1)</td>
<td class="gt_row gt_left" headers="class">L</td>
<td class="gt_row gt_left" headers="coef"></td>
<td class="gt_row gt_left" headers="group"></td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">L</td>
<td class="gt_row gt_left" headers="coef"></td>
<td class="gt_row gt_left" headers="group">Question</td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">L</td>
<td class="gt_row gt_left" headers="coef"></td>
<td class="gt_row gt_left" headers="group">Subject</td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="prior">student_t(3, 0, 2.5)</td>
<td class="gt_row gt_left" headers="class">sd</td>
<td class="gt_row gt_left" headers="coef"></td>
<td class="gt_row gt_left" headers="group"></td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb">0</td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">sd</td>
<td class="gt_row gt_left" headers="coef"></td>
<td class="gt_row gt_left" headers="group">Question</td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">sd</td>
<td class="gt_row gt_left" headers="coef">Intercept</td>
<td class="gt_row gt_left" headers="group">Question</td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">sd</td>
<td class="gt_row gt_left" headers="coef">TreatB</td>
<td class="gt_row gt_left" headers="group">Question</td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">sd</td>
<td class="gt_row gt_left" headers="coef"></td>
<td class="gt_row gt_left" headers="group">Subject</td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">sd</td>
<td class="gt_row gt_left" headers="coef">Intercept</td>
<td class="gt_row gt_left" headers="group">Subject</td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="prior"></td>
<td class="gt_row gt_left" headers="class">sd</td>
<td class="gt_row gt_left" headers="coef">TreatB</td>
<td class="gt_row gt_left" headers="group">Subject</td>
<td class="gt_row gt_right" headers="resp"></td>
<td class="gt_row gt_right" headers="dpar"></td>
<td class="gt_row gt_right" headers="nlpar"></td>
<td class="gt_row gt_right" headers="lb"></td>
<td class="gt_row gt_right" headers="ub"></td>
<td class="gt_row gt_left" headers="source">default</td>
</tr>
</tbody>
</table>
</div>

</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-priors" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="43-Modelado_files/figure-html/fig-priors-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8.7: Distribuciones a priori del modelo Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Question).</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Es importante asegurar que el entrenamiento ha convergido a su distribución a posteriori. En la tabla de resumen constatamos que el valor de <code>Rhat</code> es inferior a 1.1 y el de <code>ESS</code> superior a 400 en todos los parámetros, que son umbrales que no se deberían violar <span class="citation" data-cites="burkner2019">(ver <a href="99-Referencias.html#ref-burkner2019" role="doc-biblioref">Bürkner y Vuorre 2019</a>)</span>. En la <a href="#fig-trace">Figura&nbsp;<span>8.8</span></a> se comprueba que las cadenas MCMC de muestreo de la distribución a posteriori se mezclan correctamente y no se aprecia autocorrelación en ninguno de las parámetros. Por último, en la <a href="#fig-predictive">Figura&nbsp;<span>8.9</span></a> se muestra una comparación entre los histogramas construidos con los datos con los intervalos de confianza marginales de la función predictiva a posteriori del modelo. En la mayoría de las preguntas, el muestreo reproduce bastante bien el histograma de respuestas. En algunas preguntas, como la <code>Q16</code> o la <code>Q17</code>, hay diferencias relevantes.</p>
<div class="cell" data-hash="43-Modelado_cache/html/fig-trace_644b2df455daf1d714bed2d667cd5887">
<div class="cell-output-display">
<div id="fig-trace" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="43-Modelado_files/figure-html/fig-trace-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8.8: Cadenas MCMC del modelo Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Question).</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-predictive" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="43-Modelado_files/figure-html/fig-predictive-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8.9: Comparación de los valores reales con los obtenidos a partir de la función predictiva a posteriori del modelo Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Question).</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>En cuanto a las conclusiones que podemos extraer del modelo, la más importante es que, como hemos constatado desde el principio de este trabajo, los alumnos perciben claramente una diferencia entre los niveles de subtitulado <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span>, siendo preferido el <span class="math inline">\(A\)</span>. En la <a href="#fig-predictive-2">Figura&nbsp;<span>8.10</span></a> se representan gráficamente los valores esperados de la probabilidad de respuesta a cada pregunta por tratamiento y periodo. Lo más interesante es confirmar la existencia de sendos efectos periodo y secuencia de pequeña magnitud que se materializan en que, para el nivel de subtitulado <span class="math inline">\(A\)</span>, son ligeramente más probables las respuestas con valor 4 en el periodo 2 (secuencia <span class="math inline">\(BA\)</span>) que en el 1 (secuencia <span class="math inline">\(AB\)</span>). Con las respuestas de valor 5 ocurre lo contrario: en el subtitulado <span class="math inline">\(A\)</span> son más probables en el periodo 1 (secuencia <span class="math inline">\(AB\)</span>) que el 2 (secuencia <span class="math inline">\(BA\)</span>). Esto ya lo habíamos constatado antes en el análisis del <span class="math inline">\(OR\)</span> (ver <a href="42-Analisis.html#sec-or"><span>Sección&nbsp;7.2.3</span></a>).</p>
<div class="cell" data-hash="43-Modelado_cache/html/fig-predictive-2_08809b9075f57a665c8cec8a5b7ce2bd">
<div class="cell-output-display">
<div id="fig-predictive-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="43-Modelado_files/figure-html/fig-predictive-2-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8.10: Muestreo de la esperanza de la función predictiva a posteriori por tratamiento, periodo y pregunta del modelo Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Question).</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Constatados los efectos periodo y secuencia, y sabiendo que son de pequeña magnitud, pasamos ahora a hacer un análisis de las predicciones que realiza el modelo sobre la distribución de respuestas en cada pregunta. Para ello en la <a href="#fig-pred-3">Figura&nbsp;<span>8.11</span></a> se representan 50 muestras de la esperanza de la distribución predictiva a posteriori para cada pregunta y nivel de subtitulado marginalizadas por periodo y estudiante. La primera conclusión que podemos extraer es que el modelo tiene bastante incertidumbre sobre los valores de respuesta a cada pregunta no superando casi nunca el 50% de probabilidad para todas las preguntas y niveles de subtitulado. En general se observa en la mayoría de las preguntas del nivel de subtitulado <span class="math inline">\(A\)</span> que los alumnos están bastante seguros de que la respuesta a las preguntas debe ser 4 ó 5, asignando una muy baja probabilidad a los valores 1, 2, ó 3, pero habiendo bastante confusión respecto cuál de los dos valores (4 ó 5) asignar. En el nivel de subtitulado <span class="math inline">\(B\)</span> la situación es bastante más confusa. Aunque la opción de respuesta preferida es 4 y las menos preferidas son la 5 y la 1, hay bastante mezcla entre las opciones de respuesta 2, 3 y 4. En cuanto al análisis individualizado por pregunta podemos extraer las siguientes conclusiones:</p>
<ul>
<li><p>En las preguntas <span class="math inline">\(Q04\)</span> y <span class="math inline">\(Q13\)</span> los estudiantes no aprecian defectos en el subtitulado ni diferencias entre un nivel y otro. Son valoradas en ambos niveles con puntuaciones de 4 y de 5.</p></li>
<li><p>En las preguntas <span class="math inline">\(Q15\)</span>, <span class="math inline">\(Q16\)</span> y <span class="math inline">\(Q17\)</span>, la opción de respuesta más probable es 4 en ambos subtitulados. El modelo asigna una baja probabilidad de respuesta a la opción 1 y similares al resto. La probabilidad de la opción 5 decrece ligeramente entre subtitulado <span class="math inline">\(A\)</span> y <span class="math inline">\(B\)</span> y lo contrario ocurre con las opciones 2 y 3.</p></li>
<li><p>Las preguntas <span class="math inline">\(Q01\)</span>, <span class="math inline">\(Q02\)</span>, <span class="math inline">\(Q03\)</span>, <span class="math inline">\(Q10\)</span>, <span class="math inline">\(Q11\)</span> y <span class="math inline">\(Q12\)</span> son similares a las anteriores. Particularmente en lo referente a que la respuesta más probable en el subtitulado <span class="math inline">\(B\)</span> es 4. En el subtitulado <span class="math inline">\(A\)</span> hay preferencia por 4 y 5. El nivel 5 cae acusadamente en el subtitulado <span class="math inline">\(B\)</span> y en este nivel aumenta ligeramente la probabilidad de respuesta 2 y 3.</p></li>
<li><p>Las preguntas <span class="math inline">\(Q06\)</span>, <span class="math inline">\(Q07\)</span>, <span class="math inline">\(Q14\)</span> y <span class="math inline">\(Q18\)</span> no son muy diferentes de las anteriores. En general el modelo predice mayor probabilidad de respuesta para 5 en el subtitulado <span class="math inline">\(A\)</span> pero este valor es con alta probabilidad cercano a cero en el subtitulado <span class="math inline">\(B\)</span>. En el subtitulado <span class="math inline">\(B\)</span> la probabilidad de respuesta 2, 3 ó 4 es similar.</p></li>
<li><p>Las preguntas <span class="math inline">\(Q05\)</span>, <span class="math inline">\(Q08\)</span> y <span class="math inline">\(Q09\)</span> son las que más diferencias entre subtitulados presentan. La respuesta más probable en el subtitulado <span class="math inline">\(A\)</span> es 5 (en <span class="math inline">\(Q08\)</span> y en <span class="math inline">\(Q09\)</span> muy parecida a 4). Por contra, en el subtitulado <span class="math inline">\(B\)</span> las respuestas 4 y 5 tienden a cero, siendo la más probable la respuesta 2. En <span class="math inline">\(Q05\)</span> y en <span class="math inline">\(Q09\)</span> la segunda respuesta más probable al subtitulado <span class="math inline">\(B\)</span> es 1 y 4 en la <span class="math inline">\(Q08\)</span>.</p></li>
</ul>
<p>En definitiva, nuestro modelo predice que los estudiantes están bastante de acuerdo en que en las preguntas <span class="math inline">\(Q05\)</span> y <span class="math inline">\(Q09\)</span> hay una diferencia de calidad importante entre subtitulados. También están de acuerdo en que en las preguntas <span class="math inline">\(Q04\)</span> y <span class="math inline">\(Q13\)</span> no hay apenas cambio entre los subtitulados. En las preguntas <span class="math inline">\(Q15\)</span>, <span class="math inline">\(Q16\)</span> y <span class="math inline">\(Q17\)</span> hay una gran confusión en ambos niveles de subtitulado y en el resto la confusión se circunscribe al nivel de subtitulado <span class="math inline">\(B\)</span>, ya que en el nivel <span class="math inline">\(A\)</span> las opciones 4 y 5 predominan.</p>
<div id="fig-pred-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="images/bayes-preg.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figura&nbsp;8.11: Muestreo de la función predictiva a posteriori por tratamiento y pregunta del modelo Response ~ Treat * Period + (1 + Treat | Subject) + (1 + Treat | Question).</figcaption><p></p>
</figure>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-bruin2011" class="csl-entry" role="listitem">
Bruin, J. 2011. <span>«How do I interpret the coefficients in an ordinal logistic regression in R»</span>. 2011. <a href="https://stats.oarc.ucla.edu/r/faq/ologit-coefficients">https://stats.oarc.ucla.edu/r/faq/ologit-coefficients</a>.
</div>
<div id="ref-burkner2021" class="csl-entry" role="listitem">
Bürkner, Paul-Christian. 2021. <span>«Bayesian Item Response Modeling in R with brms and Stan»</span>. <em>Journal of Statistical Software</em> 100 (noviembre). <a href="https://doi.org/10.18637/jss.v100.i05">https://doi.org/10.18637/jss.v100.i05</a>.
</div>
<div id="ref-burkner2019" class="csl-entry" role="listitem">
Bürkner, Paul-Christian, y Matti Vuorre. 2019. <span>«Ordinal Regression Models in Psychology: A Tutorial»</span>. <em>Advances in Methods and Practices in Psychological Science</em> 2 (febrero): 251524591882319. <a href="https://doi.org/10.1177/2515245918823199">https://doi.org/10.1177/2515245918823199</a>.
</div>
<div id="ref-chen2021" class="csl-entry" role="listitem">
Chen, Ding-Geng, y Jenny Chen. 2021. <em>Statistical Regression Modeling with R: Longitudinal and Multi-level Modeling</em>. <a href="https://doi.org/10.1007/978-3-030-67583-7">https://doi.org/10.1007/978-3-030-67583-7</a>.
</div>
<div id="ref-ordinalR" class="csl-entry" role="listitem">
Christensen, R. H. B. 2022. <span>«ordinal—Regression Models for Ordinal Data»</span>.
</div>
<div id="ref-christensen2018CumulativeLM" class="csl-entry" role="listitem">
Christensen, Rune Haubo Bojesen. 2018. <span>«Cumulative Link Models for Ordinal Regression with the R Package ordinal»</span>. En.
</div>
<div id="ref-frienly2015-2" class="csl-entry" role="listitem">
Friendly, Michael. 2015. <em>Classification and regression trees</em>.
</div>
<div id="ref-gelman2013" class="csl-entry" role="listitem">
Gelman, Andrew, John Carlin, Hal Stern, David Dunson, Aki Vehtari, y Donald Rubin. 2013. <em>Bayesian Data Analysis</em>. <a href="https://doi.org/10.1201/b16018">https://doi.org/10.1201/b16018</a>.
</div>
<div id="ref-harrell2015" class="csl-entry" role="listitem">
Harrell, Frank. 2015. <em>Regression Modeling Strategies: With Applications to Linear Models, Logistic and Ordinal Regression, and Survival Analysis</em>. <a href="https://doi.org/10.1007/978-3-319-19425-7">https://doi.org/10.1007/978-3-319-19425-7</a>.
</div>
<div id="ref-Levshina2020" class="csl-entry" role="listitem">
Levshina, Natalia. 2020. <span>«Conditional Inference Trees and Random Forests»</span>. En <em>A Practical Handbook of Corpus Linguistics</em>, editado por Magali Paquot y Stefan Th. Gries, 611-43. Cham: Springer International Publishing. <a href="https://doi.org/10.1007/978-3-030-46216-1_25">https://doi.org/10.1007/978-3-030-46216-1_25</a>.
</div>
<div id="ref-kruschke2018" class="csl-entry" role="listitem">
Liddell, Torrin M., y John K. Kruschke. 2018. <span>«Analyzing ordinal data with metric models: What could possibly go wrong?»</span> <em>Journal of Experimental Social Psychology</em> 79: 328-48. <a href="https://doi.org/10.1016/j.jesp.2018.08.009">https://doi.org/10.1016/j.jesp.2018.08.009</a>.
</div>
<div id="ref-Liu2202" class="csl-entry" role="listitem">
Liu, Xing. 2022. <em>Categorical Data Analysis and Multilevel Modeling Using R</em>. Editado por SAGE Publications Ltd.
</div>
<div id="ref-oconnell2006" class="csl-entry" role="listitem">
O’Connell, Ann. 2006. <em>Logistic Regression Models for Ordinal Response Variables</em>. <a href="https://doi.org/10.4135/9781412984812">https://doi.org/10.4135/9781412984812</a>.
</div>
<div id="ref-MASSR" class="csl-entry" role="listitem">
Venables, W. N., y B. D. Ripley. 2002. <em>Modern Applied Statistics with S</em>. Fourth. New York: Springer. <a href="https://www.stats.ox.ac.uk/pub/MASS4/">https://www.stats.ox.ac.uk/pub/MASS4/</a>.
</div>
<div id="ref-VGAMR" class="csl-entry" role="listitem">
Yee, T. W. 2023. <em><span>VGAM</span>: Vector Generalized Linear and Additive Models</em>. <a href="https://CRAN.R-project.org/package=VGAM">https://CRAN.R-project.org/package=VGAM</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Se han realizado simulaciones con otras combinaciones de variables explicativas que no se incluyen por no haber producido resultados relevantes.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>En la práctica los coeficientes estimados con las funciones de enlace <code>probit</code> y <code>logit</code> suelen similares.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>En el siguiente apartado se demuestra esta fórmula.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>El número de condición de Hessiano es una medida de la curvatura de una función en un punto. Si el número de condición de Hessiano es grande, la función es muy sensible a pequeñas perturbaciones y puede ser difícil de optimizar.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>El test de Wald es un contraste de hipótesis estadístico en el que se evalúa si el valor estimado es cero suponiendo que <span class="math inline">\(W = \left(\frac{\hat{\theta} - \theta_0}{se(\hat{\theta})}\right)^2 \sim \chi^{2}\)</span> .<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Ver <a href="77-Contrasts.html"><span>Apéndice&nbsp;C</span></a> para una discusión sobre el significado y la interpretación de los contrastes <code>treatment</code> y <code>sum</code>.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Los interceptores sí son iguales.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Los umbrales tienen los mismos valores pero de signo contrario debido a diferencias en la parametrización del modelo en cada función utilizada.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./42-Analisis.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Análisis estadístico.</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./50-Resultados.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Resultados</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>